### ISSUE TITLE
Auth0AuthApi : authorize_with_ro/device

### ISSUE THREAD

**Issue by udf2457** [auth0/auth0-PHP#100]
I've a question about authorize_with_ro in Auth0AuthApi.

Surely the device parameter should be outside of "if ($id_token !== null)" ?

I don't see what purpose $id_token fulfills ?  Also, testing with https://auth0.com/docs/api/authentication#!#post--oauth-ro, the id_toke parameter is not required when using offline_access and device.

**Comment by glena** [comment]
it make sense when you request an access token using the offline access scope. I will try to add this change soon with the new release

**Comment by glena** [comment]
I released `4.0.0` with this fix. Note that there are some API changes and the old one will be soon deprecated (not a big change tho). Check the readme for the changes on how to authenticate, use the authentication api, management api and verify tokens
