### ISSUE TITLE
Method to retrieve refresh token

### ISSUE THREAD

**Issue by drewsymo** [auth0/auth0-PHP#101]
Hi,

Is there a way to fetch the refresh token from the request?

I can see it if I:

```
        private function exchangeCode(): ...
           var_dump($auth0_response);
           die();
```

I'd like to store this on the user (backend only) so I can renew their token if their session is about to expire.

**Comment by glena** [comment]
yes, it should be here https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L246-L248

I will throw a new release next week with that

**Comment by glena** [comment]
v4 was released.

There are some classes soon to be deprecated, check the readme for more info (o the classes comments)
