### ISSUE TITLE
Linked Accounts

### ISSUE THREAD

**Issue by drewsymo** [auth0/auth0-PHP#103]
Hi there,

Understandably this might be more of an Auth0 issue rather than the PHP SDK issue, but I'm wondering how we can get the primary users JWT after login?

e.g.

1. User registers using Facebook
2. User signs out
3. User comes back and registers with Google

How do we obtain the token of the Facebook account when the user logs in with a secondary account? We require this token so we can continue to make authenticated API calls to the users initial (primary) account.

**Comment by glena** [comment]
So you have a user that has two identities linked, facebook (primary) and google (Secondary), right?

Now you are trying to get the facebook access token to call the facebook api?

in that case, you should call the management API (GET /api/v2/users/{id}) to fetch the entire user profile and check the identities collection. You will find one identity for each user linked. Filter them by the provider (in this case facebook) and you should get the access token there.

**Comment by drewsymo** [comment]
Hey Glena,

Thanks for your help with this one.

We don't need the access token but we do need the id_token. Imagine you have the following scenario:

1. Client logs in with Facebook.
2. Client has an account created on our PHP app with the username: facebook|23283237.
3. Client then logs in with Google.
4. Client can no longer pull their original account details from our API as the token is different.

So we need a way to achieve:

1. Client logs in with Facebook
2. Client then logs in with Google
3. Auth0 returns the JWT of the Facebook identity, not the Google identity

**Comment by glena** [comment]
Ok, so you never linked the accounts then?

If you link both accounts, it will always answer with the main identity id (check this doc about account linking https://auth0.com/docs/link-accounts).

You have two options:

- link accounts using rules: the issue with that, is that the main identity will be always the secondary one if you link both accounts when the user logs in with Google. You can solve this using another rule to add a new attribute (Claim) in the token with the main identity id.

- link accounts in your app: check if the user already exists on your app (maybe using the email?) and if this is the case, redirect the user to a page to link users. There you will need to ask the user to authenticate with the identity that already exists in your site, and once you have both user_id, link them together.
