### ISSUE TITLE
Undefined user_metadata error thrown

### ISSUE THREAD

**Issue by Crecket** [auth0/auth0-PHP#108]
When I try to get the user_metadata it will throw a error since the user's meta data is not set by default. #107
```PHP
$Auth0 = new Auth0\SDK\Auth0(
// options
);
$app['Auth0']->getUserMetadata();
```
This causes:
```
ContextErrorException in Oauth2Client.php line 333:
Notice: Undefined index: user_metadata
```

This can easily be solved by returning a empty array or NULL if no metadata is set.

**Comment by glena** [comment]
Released as `4.0.1`
