### ISSUE TITLE
RS256 Signing - Code incomplete

### ISSUE THREAD

**Issue by adamgoose** [auth0/auth0-PHP#109]
Looks like someone was working on RS256 signing, and didn't get around to finish it. :P

- [x] A `self` method is called [here](https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php#L96), but the method does not exist. It appears to be deprecated, in favor it `Auth0\SDK\Helpers\JWKFetcher@fetchKeys()`.
- [x]  There's an added slash [here](https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/JWKFetcher.php#L38)

**Comment by adamgoose** [comment]
Will work on a PR tomorrow.

**Comment by glena** [comment]
Dont know what happened there... on it. Thx for reporting

**Comment by glena** [comment]
fixed, can you check the branch `4.x.x-dev` before merging? You should be able to install it using `dev-4.x.x-dev` as the version in composer

**Comment by adamgoose** [comment]
LGTM

**Comment by glena** [comment]
released `4.0.3`
