### ISSUE TITLE
Redirect URL in jobs->sendVerificationEmail

### ISSUE THREAD

**Issue by stadskle** [auth0/auth0-PHP#117]
Hi,

There is one feature that would be great (and simple) to add in the SDK that I now have to make a custom API call to do. That is adding a redirectURL to sendVerificationEmail.

Today the code is like this (https://github.com/auth0/auth0-PHP/blob/master/src/API/Management/Jobs.php):
```php
<?php
public function sendVerificationEmail($user_id) 
  {
    return $this->apiClient->post()
      ->jobs()
      ->addPath('verification-email')
      ->withHeader(new ContentType('application/json'))
      ->withBody(json_encode([
        'user_id' => $user_id
      ]))
      ->call();
  }
?>
```

I suggest:
```php
<?php
public function sendVerificationEmail($user_id, $result_url = null) 
  {
    return $this->apiClient->post()
      ->jobs()
      ->addPath('verification-email')
      ->withHeader(new ContentType('application/json'))
      ->withBody(json_encode([
        'user_id' => $user_id,
       'result_url' => $result_url
      ]))
      ->call();
  }
?> 
```

**Comment by glena** [comment]
looks good, can you send a PR? I can merge it right away and make it faster.

BTW, if `$result_url` is null, it should not add it to the body like other endpoints.

**Comment by stadskle** [comment]
Pull request created (https://github.com/auth0/auth0-PHP/pull/118). Let me know if there are any issues, first time I made PR to public repo.

**Comment by glena** [comment]
merged! thank you
