### ISSUE TITLE
Unity

### ISSUE THREAD

**Issue by glena** [auth0/auth0-PHP#125]
- [x] New oauth/token client (generic)
- [x] oauth/token: password
- [x] oauth/token: code
- [x] oauth/token: refresh token
- [x] oauth/token: password realm
- [x] remove oauth2 client and update examples to use oauth/token code
- [ ] Deprecate tokeninfo (new release with the notice)
- [x] Remove tokeninfo for next major
- [x] Confirm it is using only userinfo
- [x] Confirm it is using only logout v2 (remove other endpoint if not)

**Comment by joshcanhelp** [comment]
I don't see the `tokeninfo` endpoint being used anywhere anymore ...
