### ISSUE TITLE
Rework tests

### ISSUE THREAD

**Issue by glena** [auth0/auth0-PHP#128]
We need to rework the tests to mock all the api requests.

An option is to inject the HTTP client so we can easily mock it and also we support any kind of client (we can create a new package auth0-php-guzzle and let people implement their own as long it has the same interface).

**Comment by cocojoe** [comment]
Hopefully #158 will make this job easier 😄

**Comment by Nyholm** [comment]
Yes, It will. 

I can look into improve this

**Comment by cocojoe** [comment]
Also we need lots more tests in general. But this is a good starting point.

**Comment by cocojoe** [comment]
Let's look at http://guzzle3.readthedocs.io/testing/unit-testing.html
