### ISSUE TITLE
User info is empty when looking up in EU account

### ISSUE THREAD

**Issue by SeanZicari** [auth0/auth0-PHP#129]
I'm using the SDK on two different sites. The code is identical on both sites. However, user info comes back empty on a site deployed to Korea using an EU auth0 account.

Is this a known issue? Is there something I can do to troubleshoot why this is happening?

**Comment by glena** [comment]
I just try it and works fine with an EU account. 
Do you have rules in the EU account?
There might be a rule messing up with the user profile.

**Comment by SeanZicari** [comment]
Thanks for trying, @glena. I disabled the only rule I had set up, but same result. I don't think it's a rule because auth0 registers the login as successful. It's just the PHP SDK that doesn't seem to find the user.

**Comment by glena** [comment]
and do you see any error on the server?

if you get the access token and makes a curl request to the userinfo endpoint (https://auth0.com/docs/api/authentication#get-user-info), does it work?

`curl -H "Authorization: Bearer {ACCESS_TOKEN}" https://{account}.auth0.com/userinfo`

replace `{ACCESS_TOKEN}` with the access token you got from auth0 and `{account}` with your account name.

**Comment by SeanZicari** [comment]
Hm. I got the expected response back from the procedure you outlined. I'm not sure why it isn't working in my application, though.

**Comment by SeanZicari** [comment]
It's pretty clear by now that the problem is in my PHP configuration somewhere. Are there any dependencies that are just expected to be installed on the server, that are _not_ installed through composer?

**Comment by SeanZicari** [comment]
@glena I figured out what the issue is. On my server, `$_REQUEST` is being sanitized, but the auth0 lib is trying to get the `code` $_GET param from it. Do you have any recommendations for fixing this issue? Thanks!

**Comment by glena** [comment]
Oh I get it. 

Well you have two options, you fork the sdk and add a param to the `exchangeCode` method so you can inject the code and avoid trying to get it from `$_REQUEST` and then send a PR  :) https://github.com/auth0/auth0-PHP/blob/master/src/API/Oauth2Client.php#L239

I can release a patch version for v4 with that change and include it in the next version (v5) that will be released soon. For older versions you can either upgrade to v4 (should be easy) or fork it as I said before.

**Comment by SeanZicari** [comment]
Opened PR #130.

**Comment by SeanZicari** [comment]
For now, I've changed my local auth0 install to use `$_GET`. I will be revisiting the PR when I have time to finish debugging it.

Do you have any advice for understanding what failed? I couldn't find definitive failure info from the test output.

**Comment by glena** [comment]
I guess you might have the `request_order` configuration different between environments. (http://php.net/manual/en/ini.core.php#ini.request-order).

PHP can merge GET POST and COOKIES into REQUEST but you can tweak that. Since having COOKIE is not a good idea some people changes that configuration and in your case it might be missing GET.

Anyway, it is a good idea to move away from REQUEST and in fact, the upcoming version does not uses it (to enforce it, it checks GET or POST based on the response_mode configured in the SDK).

**Comment by glena** [comment]
`4.0.9` is out with your PR
