### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by brandonwilliams** [auth0/auth0-PHP#136]
Hi, beginner question:
If I wanted to connect to my own localhost Mysql database to retrieve and return data from within a secure function (in a secured route), what is the best way to do that? I seem to be getting a lot of "unexpected end of json input" errors from my angular 2 authHttp calls. Thanks.

**Comment by brandonwilliams** [comment]
Error on my part. The data itself was messing with my json. Had to utf8_encode($string) my data.

**Comment by glena** [comment]
I was answering when your comment came in, glad you find out

**Comment by brandonwilliams** [comment]
Thanks
