### ISSUE TITLE
Passing parameters/variables via get or post

### ISSUE THREAD

**Issue by brandonwilliams** [auth0/auth0-PHP#140]
Is there any built-in system for retrieving get (or post) params/variables, or should we just do it the regular $_GET['search-term'] way?

Ex: $router->get('/secured/search/{search-term}', function() use ($app){ ... }

(where search-term is passed as a variable), and if so, does it clean input automatically?

Thanks.

**Comment by brandonwilliams** [comment]
I just realized that this is a bramus/router issue... 

...aaaaand found it right away. lol

**Comment by glena** [comment]
hahahah good :)
