### ISSUE TITLE
JWTVerifier RS256 example is misleading

### ISSUE THREAD

**Issue by Jakooth** [auth0/auth0-PHP#142]
I was struggling to authenticate with RS256 until finally I decided to debug the JWTVerifier method.
It came up the 'authorized_iss' => [$domain] must be strictily in this format:
"https://yourdomain.eu.auth0.com/"

In all other use cases from JavaScript or PHP the domain part "https:// ... /" is not required, but here the id_token is decoded with the entire URL and without the HTTP prefixes it will fail to match. For example the Management API will fail, if you give the $domain with prefixes.

I recommend you have a note about this in the example.

**Comment by glena** [comment]
you are right, I will change this in the README. thx
