### ISSUE TITLE
auth0-php out of date.

### ISSUE THREAD

**Issue by nnats** [auth0/auth0-PHP#144]
auth0-php is out of date on composer.json, the last version is 5.0.2.

![image](https://cloud.githubusercontent.com/assets/20141842/23594113/ee079634-01f5-11e7-9f35-484ac1a35890.png)

![image](https://cloud.githubusercontent.com/assets/20141842/23594117/f34f69fa-01f5-11e7-9106-262b56232931.png)

**Comment by glena** [comment]
Sorry, which composer.json are you talking about?
is it the api example?

**Comment by nnats** [comment]
Hello German

I see that I've missed the reference to the specific folder, sorry for that, but you guess it, and not only that, you fixed it with this commit https://github.com/auth0/auth0-PHP/commit/415bf49b11d672119d87ab34d6b47a9e1fbb1b7a#diff-ad0c22b2778299f3a1cffb85280601d9

**Comment by glena** [comment]
🙌 good
