### ISSUE TITLE
Error 401 Unauthorized.

### ISSUE THREAD

**Issue by nnats** [auth0/auth0-PHP#145]
The Sample project is resulting in a 401 error even though all the readme.md suggestions are followed trough, a recent change to the code sample was made and needs to be specified in the documentation how to handle it.

Steps to reproduce:
- Download sample project.
- Adjust .env file as requested.
- Start the server.
- Make a request from postman adding Authorization -IDTOKEN- as Headers.

Expected result: Shh, it's secret message.

Actual Result: Invalid Token message.

**Comment by glena** [comment]
Did you download this one https://github.com/auth0/auth0-PHP/tree/master/examples/basic-api or from the docs page?

**Comment by nnats** [comment]
Yes, that one, the same link is given in the quickstart page of this API. If I had to make a quick guess, I'll say the steps documented won't be enough after this https://github.com/auth0/auth0-PHP/commit/dce584cc1282c7c8ecbb2a5e2311c64dc78e8da1#diff-c975ed3f9f6da8de7c99c34fba267499

**Comment by glena** [comment]
That is because that sample was change to work with RS signed tokens, take a look to this one https://github.com/auth0-samples/auth0-php-api-samples/tree/master/02-Authenticate-HS256

BTW we are in the process to update the PHP quickstarts in based on the recent changes, sorry for the confusion.
