### ISSUE TITLE
Cannot new up an Oauth2Client instance

### ISSUE THREAD

**Issue by mbadolato** [auth0/auth0-PHP#150]
```Oauth2Client``` is dependent on the ```Oauth\Client``` class from the ```adoy/oauth2``` package. This package is not in the composer require block in 5.0.3, so trying the new up an instance faills

```php
<?php

use Auth0\SDK\API\Oauth2Client;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/environment_loader.php';

$params = [
    'domain'                => getenv('AUTH0_DOMAIN'),
    'client_id'             => getenv('AUTH0_CLIENT_ID'),
    'client_secret'         => getenv('AUTH0_CLIENT_SECRET'),
    'redirect_uri'          => getenv('AUTH0_REDIRECT_URI'),
    'persist_id_token'      => true,
    'persist_refresh_token' => true,
];

$provider = new Oauth2Client($params);
```

![screen shot 2017-03-22 at 1 26 12 pm](https://cloud.githubusercontent.com/assets/164615/24219188/297da130-0f03-11e7-86d7-ccfab8b6b359.png)

**Comment by mbadolato** [comment]
Just ran a code coverage test on the library and saw that ```Oauth2Client``` is not touched by the suite, explaining how this bug made it into the wild.

Given that ```Auth0.php``` is deprecated as of 4.0 and that ```Authorization``` and ```Oauth2Client``` are the recommended replacements (per the [README)](https://github.com/auth0/auth0-PHP/blob/master/README.md#40), this should probably be considered a showstopper, especially given that it's broken in what is deemed a stable release of the library

**Comment by glena** [comment]
This is the correct way to handle this https://github.com/auth0/auth0-PHP#oauth2-authentication
