### ISSUE TITLE
supported_algs or supported_algs ?

### ISSUE THREAD

**Issue by tonylucas** [auth0/auth0-PHP#152]
Hi,

I spent long and long hours to debug my code.

In "Getting started" section there is in the example : 
`'supported_algs' => ['RS256'],`

In JWTVerifier.php file : 
` if (isset($config['suported_algs']))`

So it won't ever work because it's not written the same way... 👎

**Comment by glena** [comment]
it is fixed in the latest version https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php#L73

which version are you using?

**Comment by tonylucas** [comment]
Yes it was an older version, I don't know why composer didn't installed the latest.

**Comment by glena** [comment]
maybe cache? 

glad it works fine now

**Comment by tonylucas** [comment]
I have another question about this parameter :
`'valid_audiences' => [$client_id]`

In my configuration it is only working if I provide an audience like https://***.eu.auth0.com/api/v2/
And it doesn't work if I provide a client_id.

**Comment by glena** [comment]
Can you show me how are you authenticating the user?

Seems you are getting an access token asking for the management api audience.

If you use an id_token to call your API, you should use the client_id (we are recommending not to do this, we are working on the docs so some of them might be outdated)

In your case you might be using the access token, in that case you should create an api in the dashboard (https://manage.auth0.com/#/apis) representing your API (you can set custom scopes if you need to) and then ask for that audience when you redirect the user to the hosted login page (or when calling oauth/token)

**Comment by tonylucas** [comment]
In fact I have no user, I just want to secure requests between a Vue.js client app and a PHP API.

If I set client_id as valid_audience, and if I try to verifyAndDecode a token, I get "this token is not intended for us".

**Comment by glena** [comment]
`In fact I have no user` so how do you get the token?

**Comment by tonylucas** [comment]
I get the token by issuing a post request to https://***.eu.auth0.com/oauth/token 
But it needs client_secret to be sent so I think it is not the good way in client web app :/

**Comment by glena** [comment]
no, you shouldn't do that. 

Doing this is the same than not having any security at all (I can easily copy that code and issue tokens to call your api, which is the same than not having it).

**Comment by tonylucas** [comment]
Yes I am understanding this now.
So which solution should I use to secure my requests, and to be sure only my app can call the API ?

**Comment by glena** [comment]
if your app requires a user to log in, you should use the user access_token to call your apis.

If it doesn't, all the info your app has is already public so there is no point in "securing" those requests (I can easily crawl your site instead of calling your apis).
