### ISSUE TITLE
Avoid using public properties

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#159]
Example on Api\Management. 

This would be a BC break so it should be done before next major release.

**Comment by cocojoe** [comment]
I'm open to PR's for v6 😄

**Comment by Nyholm** [comment]
Of course, I will make many PRs after my major PR is merged.

**Comment by cocojoe** [comment]
I want to go through the PRs tagged as v5-Next and get that released, then branch that to start the 6.x.x branch.

**Comment by Nyholm** [comment]
Excellent!

**Comment by cocojoe** [comment]
Again I don't mind, but it's really coding style / best practice. However if it means a developer has to rewrite a load of code to migration to 6.x.x it's not so good.  The migration path should be as minimal as possible,

**Comment by Nyholm** [comment]
I agree with you on the namespaces, but this issue is more than just coding standards. I think we should reconsider in this case. 

I will send a PR with a approach that are a bit different. 

Btw, I've been doing loads of API clients. The best approach is to do something similar to https://github.com/KnpLabs/php-github-api

See example here:  https://github.com/FriendsOfApi/boilerplate

**Comment by cocojoe** [comment]
I am not dismissing this out of hand, best practice is important.  I'm simply saying that any Public API changes must offer a clean as possible migration path to ensure easy adoption of 6.x.x+ 😄 So please feel free to submit something and lets look at it.
