### ISSUE TITLE
Auth0\SDK\API\Management\Users::deleteAll does not work

### ISSUE THREAD

**Issue by magnusnordlander** [auth0/auth0-PHP#168]
Calling `Auth0\SDK\API\Management\Users::deleteAll` issues a `DELETE` HTTP request to `https://tenant.eu.auth0.com/api/v2/users`, however, that endpoint does not seem to allow `DELETE` requests, as the following exception is thrown:

```
Uncaught GuzzleHttp\Exception\ClientException: Client error: `DELETE https://tenant.eu.auth0.com/api/v2/users` resulted in a `404 Not Found` response:
{"statusCode":404,"error":"Not Found"}
```

Is that endpoint supposed to exist within the v2 API, or should the `deleteAll` method be removed?

**Comment by cocojoe** [comment]
The endpoint used to be able to delete all, however this particular endpoint now requires a userId.  
https://auth0.com/docs/api/management/v2#!/Users/delete_users_by_id

The new call is `DELETE /api/v2/allusers`

**Comment by cocojoe** [comment]
It was decided to remove this method as it's a dangerous one, it can still be accessed manually if required.
