### ISSUE TITLE
Only support PHP7

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#169]
In version 6 if this library, what if we only support PHP7? 

Scalar type hints for the win!

**Comment by cocojoe** [comment]
This will not happen anytime soon, perhaps when 5.6 reaches the end of its LTS.  This is not to say there couldn't be a PHP 7 branch in the future.

**Comment by Nyholm** [comment]
Okey. It was just an idea. 
Btw, 5.6 has not have active support for almost 6 months. http://php.net/supported-versions.php

**Comment by cocojoe** [comment]
I would rather 6.x.x improved things as they are, lots to do first. Then we can revisit in the future and perhaps it will then make sense to move 6.x.x to security fixes and then look at 7.x.x for PHP 7. All subject to change of course, @glena you have any strong thoughts on this?

**Comment by glena** [comment]
Besides 5.6 not being actively support, there is a huge amount of people still using it (believe it or not there were some customers using 5.3 pissed off because of lack of support).

Also, since it is just an SDK, I dont see a lot of gain on doing that (some syntax sugar but not big improvements)
