### ISSUE TITLE
6.x.x Launch

### ISSUE THREAD

**Issue by cocojoe** [auth0/auth0-PHP#171]
- [ ] README
- [ ] Migration Guide (Breaking Changes)
- [ ] QuickStarts

**Comment by cocojoe** [comment]
Notes: 5.6+

**Comment by cocojoe** [comment]
@glena what are your thoughts on a 6.0 pre-release, what other areas do we need to look and what related SDKs are priority (ones want actually want to maintain going forward) to migrate to 6.0? Thx

**Comment by glena** [comment]
Good idea to relase a beta so folks can test it out a little bit.
Laravel and symfony upgrades are a must (we dont need to rush tho). Also we need to figure out how to handle HTTP plug on those.

We need to:
- upgrade readme with a BC breaks notice and a mention to the new http client abstraction (and how to use it, probably just link to the http plug docs)
- quickstarts should be pretty straight forward

**Comment by Nyholm** [comment]
I would also like to see a pre release. Im working on https://github.com/happyr/auth0-bundle and would like to try out if we need anything else before a final 6.0.0.

There are some PRs open atm. I don't have anything more after those (as I know of now). May I suggest to release a alpha after the open PRs are merged?

**Comment by glena** [comment]
sounds good.

Also, that  bundle looks good @cocojoe we should add that one (once finished) in the list of SDK (community supported)

**Comment by masacc** [comment]
Hello,

any news about a release date for this version ?

**Comment by cocojoe** [comment]
@masacc there is some other work to complete. However, this will be coming back into focus in the near future.

**Comment by joshcanhelp** [comment]
I'm going to close this one out for now. We're working on a proper roadmap for this SDK now, which  include much of the improvements already in the `6.x.x` branch.
