### ISSUE TITLE
Consistent use of camelCase convention

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#178]

**Comment by cocojoe** [comment]
Perhaps we should have one issue for these types of issues and have a checklist, if we want to use it as a public tracker, vs multiple similar issues.

**Comment by Nyholm** [comment]
Hm, we do not have an overflow of issues nor PRs at the moment. So I guess it will be over kill. 

I wrote it here as a reminder for myself and also to tell you (the maintainers) what my plans are. I will start work on this when/if #176 is merged. I do not want to deal with conflicts =)
