### ISSUE TITLE
Correct way to use the JWT Token generated in API v2 if we want expanded scope

### ISSUE THREAD

**Issue by shankscoder** [auth0/auth0-PHP#19]
Hi,
We're trying to build a small management admin dashboard for our Auth0 setup, and we want to give rights to our admins in this app to create new users and update existing user data.

We've generated the token in the API v2 section, but it's not clear on how to use this token with the Auth0 PHP SDK class.

Could you share some insight on the correct way to use this?

Thanks in advance.

**Comment by glena** [comment]
Hi @shankscoder:

you should use

```
\Auth0\SDK\API\ApiUsers::create($domain, $token, $data)
```

Right now, only have a client for the users endpoints, let me know which ones do you need to use and I can add them (or you can shoot a PR based on the `ApiUsers`

**Comment by shankscoder** [comment]
Thanks. We figured this out. We're using other API endpoints as well (mainly user and app metadata), so we're directly consuming the APIs in Guzzle. 

It'd be great if you could have modular classes for each object type in the API (user, apps, etc.) so that we can pick and choose the necessary object we want to work with without having a bloated client.

**Comment by glena** [comment]
Hi, just to let you know, we added support for several new api v2 endpoints :)
The new version released is 1.0.7.
