### ISSUE TITLE
Management API must throw some exceptions

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#190]
If the response is invalid we should throw exceptions.

**Comment by cocojoe** [comment]
What kind of situations are you considering `invalid` to be?

**Comment by Nyholm** [comment]
When the server responds with 4xx or 5xx

**Comment by cocojoe** [comment]
Could probably say anything other than 2xx @glena thoughts?

**Comment by glena** [comment]
Not a fan of exceptions when the language does not forces you to handle them... but I am ok with that (with php it is not a big deal since it will break only the current request.

We should document it well (a warn somewere?)

**Comment by glena** [comment]
Not a fan of exceptions when the language does not forces you to handle them... but I am ok with that (with php it is not a big deal since it will break only the current request.

We should document it well (a warn somewhere?)

**Comment by Nyholm** [comment]
Naturally. I can create a small PR for the Blacklist API
