### ISSUE TITLE
Request for an alpha release of 6.0.0

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#191]
I would like to start to do some testing for the new 6.0.0 branch. Could we tag an Alpha pre-release?

**Comment by cocojoe** [comment]
Sure, just use the head of 6 dev branch ? I can tag it if this is necessary for whatever you're pulling it with.

**Comment by Nyholm** [comment]
Yeah. That would be great

**Comment by cocojoe** [comment]
I think certainly #188 should be in alpha, however it can go in the next minor.  For now you can play with `6.0.0-alpha.1`

If you can report back on findings.  Thx

**Comment by Nyholm** [comment]
Awesome. Thank you!
