### ISSUE TITLE
Add support for configure cache

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#192]
We want to cache some request. We should allow people passing a PSR cache to the client builder. 

See KNP/Github: https://github.com/KnpLabs/php-github-api/blob/2.5.0/lib/Github/Client.php#L355

**Comment by cocojoe** [comment]
What scenarios would I want to store responses? With an Auth API I would always expect to be requesting fresh responses?

**Comment by Nyholm** [comment]
Say /userinfo. You may want to cache that for 5 min to avoid hitting the rate limit.

**Comment by cocojoe** [comment]
I feel persistence strategy should be the responsibility of the developer, secure sessions perhaps?
@glena any strong feelings on this?

**Comment by Nyholm** [comment]
That is fine. We just add some docs for it then.
