### ISSUE TITLE
Re-add /delegation endpoint

### ISSUE THREAD

**Issue by baschny** [auth0/auth0-PHP#196]
Even thou the `/delegation` endpoint was deprecated, there is no replacement yet for this functionality (to get a token to authenticate to a third party API).

https://auth0.com/docs/api-auth/intro#delegation

Quoting:
> At the moment there is no OIDC-compliant mechanism to obtain third-party API tokens. In order to facilitate a gradual migration to the new authentication pipeline, delegation can still be used to obtain third-party API tokens. This will be deprecated in future releases.

We use that in our application and are currently stuck to 4.0.13, as it was simply removed in 5.0.0: see https://github.com/auth0/auth0-PHP/commit/9038b844e2804785f7edf64c060afcf59e2b0606#diff-42163ba9298edba20ff2a10ac2bfc2e0L357

So until there is a proper replacement for this functionality, I propose to re-add it to the Authentication API:
https://auth0.com/docs/api/authentication#delegation

**Comment by Nyholm** [comment]
Thank you for this issue. From what I can se on the authentication docs:

> This feature is disabled by default for new tenants as of 8 June 2017. Please see [Client Grant Types](https://auth0.com/docs/clients/client-grant-types) for more information.

Im not sure we should **add** removed features.

**Comment by baschny** [comment]
Ok, I understand! We are registered before 8. June, so we still have this feature available. So we will stick to 4.x for now and see how we can replace the functionality in some mid-term future.

**Comment by Nyholm** [comment]
I can tell you that version 6.0.0 will be awesome. Stay tuned =)
