### ISSUE TITLE
Feature Request: Support sending `auth0-forwarded-for` header

### ISSUE THREAD

**Issue by ashishdasnurkar** [auth0/auth0-PHP#208]
For Resource Owner Password grant, support sending end user's ip as described here https://auth0.com/docs/api-auth/tutorials/using-resource-owner-password-from-server-side#sending-the-end-user-ip-from-your-server

**Comment by Nyholm** [comment]
Have a look at the 6.x.x branch. You can easily include this yourself by using the AddHeader plugin to the http client.

**Comment by mscharley** [comment]
6.x is still in Alpha. Do you recommend using it in production already?

**Comment by Nyholm** [comment]
I've been using it in prod for a bunch of app since it was released. Though, I'm not doing much fancy things.

**Comment by cocojoe** [comment]
@mscharley No, 6.x.x should NOT be used in production.

**Comment by Nyholm** [comment]
Sorry, If I was unclear. 

@cocojoe is correct. 6.x.x SHOULD NOT be used in production. 

However, I am using it in production and it works perfectly for me.
