### ISSUE TITLE
OIDC-conformant clients return an empty profile

### ISSUE THREAD

**Issue by lekoala** [auth0/auth0-PHP#209]
When using the sdk (latest version), with a client with the option OIDC-conformant set to true (which is the default now), the profile that is returned is empty.
Any ideas why? it's very disturbing (lost an hour) before understanding what was the issue. The readme does not help at all:

```
$userInfo = $auth0->getUser();

if (!$userInfo) {
    $auth0->login();
}

var_dump($profile);
```

$profile is not even defined in this snippet...

also, with the latest sdk, adoy/oauth2 is not required by default with cause an error quite early.  That's two things that don't work out of the box.

**Comment by cocojoe** [comment]
Can you confirm the version # please, also provide the snippet you are using, please don't paste your secret.

Thx

**Comment by lekoala** [comment]
I'm using version 5.0.5

You can see that adoy/oauth2 is not in the composer file (it should be at least suggested)
https://github.com/auth0/auth0-PHP/blob/5.0.5/composer.json

Short snippet:

    $client = $this->getClient();

        try {
            $user = $client->getUser();
        } catch (Exception $ex) {
            $user = null;
            SS_Log::log($ex, SS_Log::WARN);
        }

At this point, I have the user but it is an array with "sub" as the only key

Full code available here
https://github.com/lekoala/silverstripe-auth0/blob/master/code/Auth0SecurityExtension.php

Worth mentionning : i'm not quite sure about the usage of the audience or scope or if it has any influence when OIDC-conformant client is toggled on

**Comment by cocojoe** [comment]
If OIDC has been toggled on in the dashboard, you will only receive the `sub` in the profile unless you specify an additional scope like `profile` so try setting scope to `openid profile`.

Worth take a looking through https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

**Comment by lekoala** [comment]
I tried setting the scope but it wasnt working. Maybe I should try again. Anyway since it's the default for new clients and the setting is hidden in the advanced options it would make sense to update the readme so that the snippets provided are working out of the box

**Comment by cocojoe** [comment]
I had a quick look at your code, if you are using webAuthentication you need to set it as part of the JS. Have a look at the example here:

https://auth0.com/docs/quickstart/webapp/php/01-login

Yes agree on the README it could be clearer, it's a bit of a transition. The next version of this lib 6.x will be OIDC first. Thanks for that feedback.

**Comment by lekoala** [comment]
ok that make sense. I'll try that :-) thanks for the support
