### ISSUE TITLE
Error in composer install

### ISSUE THREAD

**Issue by joskfg** [auth0/auth0-PHP#21]
Hello,

When I'm trying to install the package I receive this error:

Problem 1
    - auth0/auth0-php 1.0.6 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.5 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.4 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.3 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.2 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.1 requires firebase/php-jwt dev-master -> no matching package found.
    - auth0/auth0-php 1.0.0 requires firebase/php-jwt dev-master -> no matching package found.
    - Installation request for auth0/auth0-php ~1.0 -> satisfiable by auth0/auth0-php[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

This seems related with https://github.com/firebase/firebase-token-generator-php/issues/15

I'm following the instructions from the quickstart.

**Comment by glena** [comment]
Hi @joskfg, which quickstart are you following (regular webapp or api backend)?

Can you copy your composer.json file here to check your dependencies?

Also, try adding `"firebase/php-jwt" : "~2.2"` as a dependency in your composer.json, since it is tagged to dev-master on the package composer.json it is not actumatically downloaded due to min stability settings on your project (It will be fixed on the next release).

**Comment by joskfg** [comment]
I was following the regular webapp and it indicates do 3 requires

```
{
    "name": "test/oauth",
    "authors": [
        {
            "name": "joskfg",
            "email": "test@test.com"
        }
    ],
    "repositories": [
	{
	    "type": "git",
            "url": "https://github.com/joskfg/auth0-PHP.git"
	}
    ],
    "minimum-stability": "stable",
    "require": {
        "auth0/auth0-php": "dev-master",
        "adoy/oauth2": "dev-master",
        "vlucas/phpdotenv": "dev-master",
    }
}
```

I solved it adding 

```
"firebase/php-jwt": "dev-master"
```

to the requires, but it didn't work indicating a version.

**Comment by glena** [comment]
great, It should be solved on the next release (WIP).
Thanks for reporting.
