### ISSUE TITLE
Support for php-jwt 5

### ISSUE THREAD

**Issue by victoriafrench** [auth0/auth0-PHP#210]
When will support for php-jwt 5 be coming? We have other composer plugins that require 5 and this is becoming an issue. google/apiclient has its dependency set to 4.0 || 5.0. Will an update be coming for this?

**Comment by cocojoe** [comment]
@victoriafrench This seems like an ideal update for 6.x (although there is no firm release date for this). I had a quick look and although it is a major, there is no mention of any breaking changes or migration requirements. Did you try setting `4.0 || 5.0` out of interest?

**Comment by victoriafrench** [comment]
@cocojoe no we haven't tried yet. We are just now integrating the sdk in our site. That is the reason it came up as we were trying to figure out how to make things coexist together.

**Comment by anam-hossain** [comment]
@cocojoe Please bump `php-jwt` version to 5.0. I think, this will not break any feature.

**Comment by cocojoe** [comment]
@joshcanhelp can you take a look at this please, the min PHP for `php-jwt` 5.0 is 5.3 which is fine as our lib is min 5.5. It is however a major release so needs checked for any Breaking Changes in the API and tested.

**Comment by joshcanhelp** [comment]
@cocojoe - I ran through the 5.0 release and nothing jumps out at me. Ran through the unit tests and everything related passed. Differences in the library are here:

https://github.com/firebase/php-jwt/compare/v4.0.0...firebase:v5.0.0

Seems like the most likely candidate for issues is JWT::verify(), which we're not using at all.

**Comment by joshcanhelp** [comment]
Fixed in v5.1.0
