### ISSUE TITLE
DOC maj

### ISSUE THREAD

**Issue by devAxeon** [auth0/auth0-PHP#217]
Can you please add the #/login explanation on "redirect_uri" param in your doc ?
Spend a lot of time to find this...
Thank you

**Comment by joshcanhelp** [comment]
@devAxeon - Is this what you're talking about?

https://github.com/auth0/auth0-PHP#oauth2-authentication

You said "your doc" but we have quite a few docs out there! Did you find the answer you were looking for on or around here?

https://auth0.com/docs/quickstart/webapp/php#add-the-auth0-callback-handler
