### ISSUE TITLE
The Management API method to update tenant settings is not sending any data

### ISSUE THREAD

**Issue by jmangelo** [auth0/auth0-PHP#222]
If you do something like:

```
$auth0Api = new Management($token, $domain);

$data = [ "session_lifetime_in_minutes" => 10080 ];

$auth0Api->tenants->update($data);
```

it will throw:

> Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `PATCH https://{domain}.auth0.com/api/v2/tenants/settings` resulted in a `400 Bad Request` response: {"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object but found type null'.

The issue seem to be that `tenants->update` does not actually send the `$data`. A quick change from the current:

```
public function update($data) 
{
  return $this->apiClient->patch()
    ->tenants()
    ->settings()
    ->call();
}
```

to

```
public function update($data) 
{
  return $this->apiClient->patch()
    ->tenants()
    ->settings()
    ->withHeader(new ContentType('application/json'))
    ->withBody(json_encode($data))
    ->call();
}
```

seems to fix the issue. However, I wrote my first line of PHP code **today** so I won't even dare to submit that as a PR without confirmation from someone else.

**Comment by cocojoe** [comment]
Can you link to the line in question please.

**Comment by jmangelo** [comment]
https://github.com/auth0/auth0-PHP/blob/master/src/API/Management/Tenants.php#L42

**Comment by cocojoe** [comment]
Thanks, just checked MGMT API Docs, your proposed changes look good. Please create your first PHP PR 👍
