### ISSUE TITLE
"We can't trust on a token issued by" core exception being thrown

### ISSUE THREAD

**Issue by AlexKopen** [auth0/auth0-PHP#225]
Every time I hit my api, a "[can't trust on a token issued by](https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php#L114)" exception is being thrown by the JWT Verifier library.

Commenting out this conditional check seems to do the trick; all other token validation works as expected.  Is there any reason this exception is being thrown?

**Comment by cocojoe** [comment]
So what value are you setting for `$config['authorized_iss']` and what values are returned in the `iss`?  
https://jwt.io/

**Comment by AlexKopen** [comment]
@cocojoe , looks like I was missing a trailing slash in my `authorized_iss`.  Thank you for reminding me to double check this value
