### ISSUE TITLE
Can't search search by id

### ISSUE THREAD

**Issue by moazam1** [auth0/auth0-PHP#226]
I am using following code to search user by ID:

    $user = $this->auth0Api->users->search( [
         '⁠⁠⁠⁠identities.user_id' => '5a550810cfb31a2789348166',
          'identities.provider' => 'auth0'
    ] );

but it's returning all users. What am I doing wrong?

**Comment by joshcanhelp** [comment]
@moazam1 - The params that you're using aren't structured correctly. Array keys should one or more **Parameters** listed here:

https://auth0.com/docs/api/management/v2#!/Users/get_users

... and query format (`q` parameter) is covered here:

https://auth0.com/docs/api/management/v2/user-search

What you probably want to do is:

```php
$auth0Api = new Management( $token, $a0_domain );
$user = $auth0Api->users->search( [
	'q' => 'identities.provider:"auth0" AND identities.user_id:"5a550810cfb31a2789348166"'
] );
```
