### ISSUE TITLE
Error at Auth0JWT::encode when using custom payload

### ISSUE THREAD

**Issue by bfgasparin** [auth0/auth0-PHP#23]
The `Auth0\SDK\Auth0JWT` does not add custom payload to the generated JWT.

The following lines at`Auth0JWT::encode`:

```php
<?php
// Auth0\SDK\Auth0JWT
if ($custom_payload) {
    $custom_payload = array_merge($custom_payload, $payload);
}
```

should be:
```php
<?php
// Auth0\SDK\Auth0JWT
if ($custom_payload) {
    $payload = array_merge($custom_payload, $payload);
}
```

Is it correct or am I missing something?

**Comment by glena** [comment]
yes, you are right!
thanks, it will be fixed in the next release :)
