### ISSUE TITLE
State Handler with Custom Session Store

### ISSUE THREAD

**Issue by datasage** [auth0/auth0-PHP#233]
Currently the state handler will initialize a new session store when first created. Even if a custom session store is provided.

If a custom session store is used, it should be either able to be passed into the SessionStateHandler class or automatically used when instantiating the class.

SessionStateHandler could instead allow anything that implements StoreInterface, instead of just SessionStore.

**Comment by jspetrak** [comment]
@datasage How is that possible. Looking into the constructor code:

```php
if (isset($config['state_handler'])) {
    if ($config['state_handler'] === false) {
        $this->stateHandler = new DummyStateHandler();
    } else {
        $this->stateHandler = $config['state_handler'];
    }
} else {
    $this->stateHandler = new SessionStateHandler(new SessionStore());
}
```

when `state_handler` parameter is passed to `Auth0`, that should take it as is.

**Comment by datasage** [comment]
Currently the type hint on the session state handler class references
session store instead of the interface. So I have to duplicate it to use it.

**Comment by joshcanhelp** [comment]
@datasage - Good find, thank you! If you can put through a PR (`dev` as the base), that would be great. Otherwise, I'll handle it before the next patch release coming up.

**Comment by joshcanhelp** [comment]
Adding in 5.1.1, PR coming now
