### ISSUE TITLE
Auth0 class missing action to renew access token

### ISSUE THREAD

**Issue by jspetrak** [auth0/auth0-PHP#234]
`Auth0` class has an `Authentication` object instantiated internally. It is supposed to call this API with current session data like access/id/refresh token and perform the operations.

However the action to renew access token with refresh token is missing.

**Comment by joshcanhelp** [comment]
If you need to get a `refresh_token` or an `id_token` back from your code exchange with `oauth/token`, you need to request that using the `scope` parameter when you create a new `Auth0` instance. 

- If you only need an access token, you can omit the `scope` parameter
- If you also need an ID token, use at least `openid` ([more here](https://auth0.com/docs/scopes/current))
- If you also need a refresh token, add `offline_access` ([more here](
https://auth0.com/docs/tokens/refresh-token/current#get-a-refresh-token))

**Comment by jspetrak** [comment]
@joshcanhelp This is not about receiving id or refresh token. This is about ability to use the refresh_token to refresh the access_token. There is not a method to do that with a ready-setup Auth0.php instance, and the Authentication object is private inside the class.

**Comment by joshcanhelp** [comment]
Sorry @jspetrak, I didn't read that correctly. 

The next section down in the Refresh Token guide I sent has instructions (for anyone that is looking for a how-to):

https://auth0.com/docs/tokens/refresh-token/current#use-a-refresh-token

I agree, though, the SDK should have a method to handle that. I'll reopen and assign to myself. 

Thank you!

**Comment by jspetrak** [comment]
Perfect, thank you!

**Comment by d0cm0d** [comment]
I have the same problem. I need to get a user list from the Management class and the token gets invalid every 24 hours.

**Comment by joshcanhelp** [comment]
@d0cm0d - Actually, this is regarding a refresh token for a user session, not the Management API. The token you're generating can be given a longer expiration date when you create it (make sure to limit your scopes to only the ones you need and keep that very safe) or you can authorize your Application for that Management API and do a[ Client Credentials Grant](https://auth0.com/docs/api-auth/grant/client-credentials). If you need more assistance there, please work with our awesome [support team](https://support.auth0.com/).

**Comment by jspetrak** [comment]
@joshcanhelp How about this implementation? https://github.com/auth0/auth0-PHP/pull/257
