### ISSUE TITLE
getAppMetadata - how to use?

### ISSUE THREAD

**Issue by miking7** [auth0/auth0-PHP#248]
The README mentions that "the Auth0 class now provides two new methods to access user metadata"... but calling `$auth0->getAppMetadata();` gives error 

> "Call to undefined method Auth0\SDK\Auth0::getAppMetadata()"

Examining the code for this library, the only place `getAppMetadata()` appears is in Oauth2Client.php, and Oauth2Client doesn't seem to be referenced anywhere else.  Have I found a bug?  or am I misunderstanding something?  What is the correct way to request app_metadata?

**Comment by joshcanhelp** [comment]
Sorry for steering you wrong there, @miking7. I see what you're talking about. The `Oauth2Client` that's in there is out-of-date and needs to be deprecated at this point. 

Getting `app_metadata` or `user_metadata` for a user will come from one of the user endpoints in the Management API like [get user by ID](https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id). Quick sample:

```php
$mgmt_api = new \Auth0\SDK\API\Management( 'APP_TOKEN_HERE', 'YOU_DOMAIN_HERE' );
$user = $mgmt_api->users->get( 'USER_ID_HERE' );
if ( ! empty( $user['app_metadata'] ) ) {
    echo  '<pre>' . print_r( $user['app_metadata'], TRUE ) . '</pre>';
}
if ( ! empty( $user['user_metadata'] ) ) {
    echo  '<pre>' . print_r( $user['user_metadata'], TRUE ) . '</pre>';
}
```
