### ISSUE TITLE
Class 'JWT' not found

### ISSUE THREAD

**Issue by adamdama** [auth0/auth0-PHP#25]
It appears the namespace of the JWT class from the firebase/php-jwt has changed and therefore the usage in the Auth0 SDK no longer works.

**Comment by glena** [comment]
Hi, it is due to recen changes on the master branch. They also tagged the package before te changes, I recommend you to point to ~2.2

**Comment by glena** [comment]
I have released the version 1.0.7 that points to the right version so there is no need to add this dependency on your composer.json

**Comment by adamdama** [comment]
I tried to run composer update to fix the issue after specifying 1.0.7 for the auth0 plugin, however I got errors saying that version 2.2 of firebase/php-jwt could not be found.

I resolved this by adding "firebase/php-jwt": "v2.2.0" as a dependancy of my project.
