### ISSUE TITLE
Invalid state with 11.6.1/lock.min.js

### ISSUE THREAD

**Issue by DeweyOx** [auth0/auth0-PHP#254]
Upgraded to 5.1.1 SDK and now getting "Invalid state" 500 error behind the scenes.

Commenting out lines 344-346 of Auth0.php:

`   if (!$this->stateHandler->validate($state)) {`
`    throw new CoreException('Invalid state');`
`     }`

resolves the issue. I know additional state validation was added here and I'm assuming that bypassing this is not a long term solution.

Log in used to work perfectly fine and still does without this check, so I assume my instantiation of Auth0 is correct.

`$this->auth0 = new Auth0(array(`
`           'domain'        => AUTH0_DOMAIN,`
`          'client_id'     => AUTH0_CLIENT_ID,`
`         'client_secret' => AUTH0_CLIENT_SECRET,`
`            'redirect_uri'  => SITE_URL . 'auth',`
`            'audience' => AUTH0_DOMAIN . '/userinfo',`
`            'scope' => 'openid email'`
`        ));`

Any ideas?

**Comment by joshcanhelp** [comment]
Hi @DeweyOx ... everything is explained in the [changelog here](https://github.com/auth0/auth0-PHP/blob/master/CHANGELOG.md#510-2018-03-02). Long story short: you can turn off state validation by passing a `state_handler` parameter in your config array (the one you posted) set to `false` to turn off internal state handling in the SDK and implement your own. The `state` parameter that you see failing there is set in the `Auth0::login()` method automatically. Implementing your own state handling would just be a matter of storing it in the same way that `Auth0::login()` does (session store).
