### ISSUE TITLE
Allow changing the session key name

### ISSUE THREAD

**Issue by Geczy** [auth0/auth0-PHP#273]
Or at least allow adding a prefix/suffix

BASE_NAME = auth0_

key = user

When a user logs in, the session that gets set is `auth0__user`

I want to be able to change that

**Comment by joshcanhelp** [comment]
@Geczy - Thanks for the report here, I'll add this to our backlog 👍

**Comment by Geczy** [comment]
So this was achieved? Where's the commit history for it?

**Comment by joshcanhelp** [comment]
@Geczy - There is a merged PR mentioned above, #279 

Please note that we'll be removing the session cookie expiration control in the upcoming major. Session name will remain.
