### ISSUE TITLE
Deprecated method email_code_passwordless_verify

### ISSUE THREAD

**Issue by lemartva** [auth0/auth0-PHP#280]
Hi, I'm trying to use the method  email_code_passwordless_verify in Auth0\SDK\API/Authentication class, I'm getting this error.

`Client error: `POST https://xxxxxx/oauth/ro` resulted in a `404 Not Found` response: Not Found `

I know /oauth/ro endpoint is deprecated, what alternative I have to verify a passwordless code using this php SDK?

Thanks for your time.

**Comment by joshcanhelp** [comment]
Hi @lemartva

At the moment, we don't have a way to do that via API so you'll need to redirect to the [universal login page](https://github.com/auth0/auth0-PHP#login) (recommended) or use [Lock](https://auth0.com/docs/libraries/lock/v11).

**Comment by lemartva** [comment]
Thanks!
