### ISSUE TITLE
Array to String exception when audience is an array

### ISSUE THREAD

**Issue by rogerms** [auth0/auth0-PHP#296]
The error message should have said "Invalid audience... " but I received "Array to String conversion exception" 
The problem is on line 203 of auth0-php\src\JWTVerifier.php
I changed it to 
Invalid audience '.implode( ', ', $audience ).'; expected '.implode( ', ', $this->valid_audiences )

**Comment by joshcanhelp** [comment]
Thank you for the report here @rogerms! You're totally right, that first one should be imploded as well. I'll put through a fix ASAP.
