### ISSUE TITLE
Something is wrong with the latest release 5.3.1

### ISSUE THREAD

**Issue by kuzmaka** [auth0/auth0-PHP#303]
After `composer update` I get following error
```
In InformationHeaders.php line 128:
                                
  Undefined index: environment  
```

**Comment by joshcanhelp** [comment]
@kuzmaka - Sorry for the trouble here. This is something that changed in the last version but I'm not getting the error on my end and I'm not sure why the method that's causing this error is being called. 

Are you using the `\Auth0\SDK\API\Helpers\InformationHeaders::Extend()` method anywhere in your code?

**Comment by joshcanhelp** [comment]
@kuzmaka - Are you using the Laravel module? If so, I think I understand where the problem stems from.

**Comment by kuzmaka** [comment]
> @kuzmaka - Are you using the Laravel module? If so, I think I understand where the problem stems from. See above ☝️

Yes, exactly. Thanks for the fast reaction!
