### ISSUE TITLE
Fatal error: Uncaught Auth0\SDK\Exception\CoreException: Invalid state

### ISSUE THREAD

**Issue by ishan-nibaya** [auth0/auth0-PHP#315]
I have a problem with auth0.

There are two auth0 Applications in the project that I am working on right now. One is in PHP other one is WordPress. Both use auth0 Hosted Page.

First I opened my WordPress site in a tab in my web browser. Then I opened the same in another tab. Then tried logging in from the first tab by entering the email and the password and got the below error message.

![002](https://user-images.githubusercontent.com/36402202/51298474-af274800-1a4a-11e9-80d4-4691f1625673.JPG)

If it is a PHP site got the below error message.
![004](https://user-images.githubusercontent.com/36402202/51298503-cb2ae980-1a4a-11e9-850d-823d54c258b2.JPG)

**Comment by joshcanhelp** [comment]
@ishan-nibaya - This might not be a "fixable" issue. State is handled per browser session so when you start mixing sessions between tabs, you might cross the state values being used. That said, WordPress uses cookies to store the state value and the PHP-SDK uses sessions so the stored value is in different places. 

Can you walk me through exactly what you're doing to get this error? Step-by-step including URLs would be helpful so I can recreate on my end and see if there is a work-around. Also, just to make sure, if you walk through the login process for either app on it's own, does that work fine? 

Thanks!

**Comment by joshcanhelp** [comment]
@ishan-nibaya - This is to be expected and not a product of PHP or WordPress or anything else platform/SDK-related. [State validation](https://auth0.com/docs/protocols/oauth2/oauth-state) requires a value to be set for the user (as a session variable, like in this SDK, or in a cookie, like WordPress) and then validated during the callback. What's happening here is:

1. App #1 sets the state as a cookie or session variable and then sends that value to the hosted login page as a URL query parameter. 
2. The login page accepts this value as state for the user on your tenant domain and waits for the login. 
3. App #2 follows steps 1 and 2 above with a different value
4. Now you login with on the hosted page for App #1 but the latest state value, the one from App #2

`Auth0->exchange()` (called by `Auth0->getUser()`) throws exceptions so you'll want a `try...catch` block around that wherever it's being used. Method is here:

https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L502

For the most part, an Exception thrown here can likely be solved by clearing their PHP app session (logging out, minus a redirect to Auth0), then redirecting to login with Auth0 again.
