### ISSUE TITLE
Unused 'APP_CLIENT_SECRET' env var

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/auth0-PHP#332]
### Description

The env var APP_CLIENT_SECRET is included in the README and the tests initialization (getEnv method) but no test is using it.
**This should be safe to remove.**

Source: https://github.com/auth0/auth0-PHP/search?q=APP_CLIENT_SECRET&unscoped_q=APP_CLIENT_SECRET

### Prerequisites

[x] I have checked the [README documentation](https://github.com/auth0/auth0-PHP/blob/master/README.md).

[ ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-PHP/issues) and [PRs](https://github.com/auth0/auth0-PHP/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

**Comment by joshcanhelp** [comment]
This is used in the client credentials grant test and in the Contributing document.
