### ISSUE TITLE
Consider dropping PHP-5.x version supports

### ISSUE THREAD

**Issue by peter279k** [auth0/auth0-PHP#343]
### Description

As far as I know, the `PHP-7.0` has been released in 2016.

It's about three years and I think it's time to consider dropping `php-5.x` supports now.

Before upgrading the PHP versions, I think we have some works need to be concerned.

- Upgrade the PHPUnit version and it can let current PHP version support.
- Change into the PHPUnit namespace.
- Pakcage has been released new version and draft the released log.

**Comment by joshcanhelp** [comment]
Appreciate the feedback here, @peter279k. You are correct, PHP 5 is long out of end-of-life and no longer supported. It's on our roadmap to move this SDK to PHP 7.x. 

That said, it's perfectly functional on PHP 7.0 and higher, as noted in the Composer file.
