### ISSUE TITLE
No packagist package created for 5.5.0

### ISSUE THREAD

**Issue by kler** [auth0/auth0-PHP#346]
### Description

No packagist package created for tag `5.5.0` _(tagged 2019-06-07)_.
Latest tag as of writing this is `5.5.0`, but latest package on packagist is `5.4.0`.

I assume every tag should also be created as a package on packagist.

**Comment by joshcanhelp** [comment]
@kler - That's odd. I don't recall doing anything special for the last release or any previous. We might have a GitHub hook that's not firing properly. I'll assign to myself and check next week. Apologies for the delay but thank you for pointing it out!

**Comment by joshcanhelp** [comment]
@kler - Thanks again for the report here. Seeing this in Packagist now:

> This package is using the legacy service integration that GitHub deprecated in January 2019 and will not auto-update anymore. Please set up the new GitHub Hook for Packagist so that it starts updating again.

I just updated manually so it's available:

https://packagist.org/packages/auth0/auth0-php#5.5.0

We'll make sure this gets automated for the next release!
