### ISSUE TITLE
Bulk User Imports - I can't Use `upsert` as a paramater for the `importUsers` feature

### ISSUE THREAD

**Issue by migueliriano** [auth0/auth0-PHP#353]
### Description

I'm not able to set the parameter `upsert` when I try to import a list of users using the method `importUsers`

#### Use case

When I'm importing a list of users I would like to set the parameter `upsert` to update pre-existing users that match on the email address.

#### When the problem started
When I tried to set the parameter upsert to the `importUsers` method, I realized that I can't set this parameter, the only parameters allowed are: $file_path and $connection_id
### Prerequisites

[x] I have checked the [README documentation](https://github.com/auth0/auth0-PHP/blob/master/README.md).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-PHP/issues) and [PRs](https://github.com/auth0/auth0-PHP/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0-PHP used: `5.5`
- Version of PHP used: `7.3.4`

### Reproduction

Feature: https://auth0.com/docs/users/guides/bulk-user-imports

Method: https://github.com/auth0/auth0-PHP/blob/eafcf1a24fbf3d49412044008b752be252600e06/src/API/Management/Jobs.php#L40

I want to use the parameter `upsert`

![upsert_parameter](https://user-images.githubusercontent.com/5392202/62786079-e1a09d00-ba8f-11e9-813a-3ba60d324fb0.PNG)

**Comment by joshcanhelp** [comment]
@migueliriano - Thank you for the detailed report here! It looks like this endpoint is missing a number of options. I'll add this to our backlog and make sure it gets taken care of.

**Comment by pinodex** [comment]
I need to set the `send_completion_email` parameter as well. I'll send a PR adding those parameters to the request.
