### ISSUE TITLE
Issues with PHP Seed project

### ISSUE THREAD

**Issue by Annyv2** [auth0/auth0-PHP#38]
I receive this error when testing the seed project of PHP on Windows 7. Other people have received it aswell https://ask.auth0.com/t/error-logging-in-with-php-web-app-tutorial/1118/2 and https://ask.auth0.com/t/getting-error-some-time-while-login-or-creating-account-in-auth0/1399

![error](https://cloud.githubusercontent.com/assets/5016479/10370405/6fe08b5e-6da8-11e5-8caa-7ae419133ef1.JPG)

**Comment by glena** [comment]
Hi @Annyv2 it is produced because your computer is not in time. It should be a couple of minutes behind and it can't verify the token signature because of that.

Try to correct the time (and if you can put it in sync with an NPT server) and it should work.
