### ISSUE TITLE
Calling Auth0 Gives Database Error in Codeigniter

### ISSUE THREAD

**Issue by musaddiq-pk** [auth0/auth0-PHP#399]
Hello, I've integrated auth0 in custom PHP and it's working fine. Now I want to configured same code in CodeIgniter (PHP framework).
Now issue is that when call `$this->CI->auth0 = new Auth0([]);` it generates database error. But if I comment this line then it's working fine.
My question is that whether it is clearing other configuration?

Regards.

**Comment by joshcanhelp** [comment]
@musaddiq-pk - I'm not sure how helpful I can be here. The `Auth0` class doesn't do anything with databases at all. Could you provide a little more context here? What is the error? What is `$this->CI`?

**Comment by musaddiq-pk** [comment]
Thanks for your time, I know that `Auth0` is not needing database. I've configured `Auth0` on same hosting and domain which working fine. But using CodeIgniter I'm facing this issue. `$this->CI` is codeigniter object referencing custom PHP's `$this` . Error message is attached below.
![db-error](https://user-images.githubusercontent.com/11736070/69119517-b7ac3d00-0ab8-11ea-9e34-6b661611a1d3.png)

**Comment by joshcanhelp** [comment]
@musaddiq-pk - Again, I'm not sure how I can be helpful here. You may want to dig a little deeper into what CodeIgniter is doing, as well as the code in the referenced file.
