### ISSUE TITLE
'Invalid state' in php:558

### ISSUE THREAD

**Issue by stspilker** [auth0/auth0-PHP#409]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

My application is throwing this exception on mobile but not on other versions when using getUser().

'Auth0\SDK\Exception\CoreException' with message 'Invalid state' in
/home/content/85/8824185/html/vendor/auth0/auth0-php/src/Auth0.php:558

### Prerequisites

[x] I have checked the [README documentation](https://github.com/auth0/auth0-PHP/blob/master/README.md).

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts. [sspilker: I was recommended here by the community]

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-PHP/issues) and [PRs](https://github.com/auth0/auth0-PHP/pulls). [sspilker: other users have similar issue in community.]

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0-PHP used: 5.3
- Version of PHP used: 5.6
- Additional packages or frameworks used that might be relevant: NA
- Desktop user agent: Firefox 71.0
- Mobile user agent: Android 9 Firefox 68.0

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

The issue seems to be stemming from SessionStateHandler, more specifically validate. 

Running some validation on this code shows that self::STATE_NAME and $state are equal whether or not I am on mobile (simple test by echoing each value and visually comparing). 

Further, on Desktop Firefox the variable $valid is set to 1 which allows validate in getUser() to pass successfully and return user id.

However, on a mobile device, the variable $valid is set to blank, causing the invalid state exception.

public function validate($state)
{
    $valid = $this->store->get(self::STATE_NAME) == $state;
    $this->store->delete(self::STATE_NAME);
    return $valid;
}

**Comment by joshcanhelp** [comment]
@stspilker - Apologies for the long delay in getting back to you. Is this still an issue? Can you be more specific about "mobile" here? Are you testing on a single device or multiple? 

> However, on a mobile device, the variable $valid is set to blank, causing the invalid state exception.

`$valid` here is not a value, it's a boolean. If you're logging or outputting that value, echoing directly will not tell you much. Either use `var_dump()` or `echo $valid ? 'YES' : 'NO';`.

You can also try the `master` branch here and see if that helps. It's got a number of breaking changes from `5.3` but if you're just starting to build your application, that might not be a problem.

**Comment by joshcanhelp** [comment]
@stspilker - Give the new major a try and see if it solves your issue. If not, let us know and we'll look into it.

**Comment by ValeSauer** [comment]
I had this issue on an application that was available on two subdomains `a` and `b` but uses only `b` as an configured application domain. When user accesses `a` Auth0's nonce (aka state) was created only for `a` leading to a failing validation due to an empty session when Auth0 redirected back to the configured application url on `b`.

I solved this issue by setting php's cookie domain to `b.`. Concretely in my laravel app i set the envvar 
```SESSION_DOMAIN=b```
