### ISSUE TITLE
Feature Request: Test against more PHP versions (7.2, 7.3, 7.4)

### ISSUE THREAD

**Issue by bkuhl** [auth0/auth0-PHP#416]
### Describe the problem you'd like to have solved

We are preparing to upgrade the PHP version of our application to run against PHP 7.3 and as part of that upgrade are reviewing our composer packages and updating them, partially to gain an understanding of which ones are tested against PHP 7.3.  It looks like [tests are currently run against PHP 7.1](https://github.com/auth0/auth0-PHP/blob/master/.circleci/config.yml#L33).

### Describe the ideal solution

It'd be fantastic if there was the ability to view the test status across multiple php versions, similar to this [AWS PHP SDK Travis-CI output](https://travis-ci.org/aws/aws-sdk-php).

**Comment by joshcanhelp** [comment]
@bkuhl - Definitely nothing wrong with that! My main concern is with how long all those version will take. This package includes integration tests that need to account for rate limiting so just adding those versions might slow the checking process way down (in series means much longer total run time, in parallel means more rate limits hit).

Regardless, we appreciate the request here and will look into it when we can.

**Comment by bkuhl** [comment]
That makes perfect sense.
