### ISSUE TITLE
Support Guzzle 7

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#421]
We are soon about to release Guzzle 7. I see that this library reverted changes in version 6 alfa and went back to hard dependency on Guzzle. 

Im would recommend to support PSR-18 instead of a concrete implementation. That would avoid dependency issues with Guzzle versions. 
Btw, Guzzle 7 will support PSR-18.

**Comment by joshcanhelp** [comment]
@Nyholm - I like the idea of improving interoperability, for sure. The HTTPPlug library had the main documented methods marked deprecated and it looked like the next version would not be PHP 7.1 compatible. That's understandable but we weren't able to bump the PHP version higher than that for this major.

Would it be possible to do that and remain PHP 7.1 compat?

**Comment by Nyholm** [comment]
Of course. Httplug did a “technical” BC break to be able to use return types as required by prs18. 
Both of them require php 7.0. 
See https://packagist.org/packages/psr/http-client

About httplug v2: https://medium.com/php-fig/the-http-client-psr-9c2535132980

**Comment by jimmyjames** [comment]
Closed with #443
