### ISSUE TITLE
add custom scope and OpenID configuration to Auth0 app?

### ISSUE THREAD

**Issue by alshaikh1** [auth0/auth0-PHP#424]
Can i add custom scope, custom endpoints and some other fields to the Provider Metadata (.well-known/openid-configuration) in Auth0 app? any tutorial/example to do that? for example, I would like to add user_premiuminfo endpoint to the openid-configuration.

**Comment by joshcanhelp** [comment]
@alshaikh1 - Unfortunately not, that's a standard metadata file that the Auth0 authorization server publishes itself.
