### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by adrienbrault** [auth0/auth0-PHP#43]
The application I'm working on is using several packages using guzzle 6, which means I cannot require this package.

**Comment by glena** [comment]
Let me check what can I do. If you want to send PR I can merge it and bump the mayor version to avoid breaking BC.

**Comment by auro1** [comment]
Yes please :+1: blocker for me.

**Comment by glena** [comment]
It will be ready in v2.0
I will release it today
