### ISSUE TITLE
Renew Tokens throws nonce error

### ISSUE THREAD

**Issue by mikelinden1** [auth0/auth0-PHP#432]
#Description
When I call `$auth0->renewTokens()` with a valid access token and refresh token loaded from the store I get the following error:

`
Auth0\SDK\Exception\InvalidTokenException: Nonce value not found in application store
Stack trace:
#0 /vendor/auth0/auth0-php/src/Auth0.php(634): Auth0\SDK\Auth0->decodeIdToken('....')
#1 /vendor/auth0/auth0-php/src/Auth0.php(584): Auth0\SDK\Auth0->setIdToken('.....')
#2 /auth.php(136): Auth0\SDK\Auth0->renewTokens()
`

I don't see a way to set a nonce. `$auth0->login()` works and does not throw a nonce error at the same line.

### Reproduction

`
$auth0 = new Auth0([
        'domain' => $auth0_domain,
        'client_id' => $auth0_client_id,
        'client_secret' => getenv('AUTH0_CLIENT_SECRET'),
        'redirect_uri' => $app_domain . '/auth/callback/',
        'scope' => 'openid offline_access',
        'store' => $cookie_store,
        'persist_access_token' => true,
        'persist_refresh_token' => true,
        'persist_user' => false
]);

$access_token = $cookie_store->get('access_token');
$refresh_token = $cookie_store->get('refresh_token');

if ($access_token && $refresh_token) {
    try {                    
        $auth0->renewTokens(); // this line throws the error
        $token = $auth0->getIdToken();
    } catch (Exception $e) {
        error_log($e);
        // something went wrong - remove the tokens (user is logged out)
        $cookie_store->delete('access_token');
        $cookie_store->delete('refresh_token');
        // continue without throwing an error
    }
}
`

### Environment

> Please provide the following:

- **Version of this library used:** 7.1
- **Other relevant versions (language, server software, OS, browser):** PHP 7.3

**Comment by joshcanhelp** [comment]
@mikelinden1 - Apologies for the delay here. I see the problem there, the ID token that is returned is passed through a verification process. That process should include nonce verification when the ID token is obtained through a login process but, in this case, that won't be available. Let me discuss with the team on an approach here.

**Comment by mikelinden1** [comment]
Thanks for the response. One more question - why is a stored access token required to use a refresh token? There's a check on like 567 of auth.php which throws an error if there is no access token but never uses it later. We don't persist access tokens in our app so this has been problematic. For now I am calling the Authentication API directly to use a refresh token. Is there anything wrong with doing that?

**Comment by joshcanhelp** [comment]
> why is a stored access token required to use a refresh token?

That's there because the main use of a refresh token is to get a new access token. It's not, however, required for any reason so we'll take a look at that as well. 

>  For now I am calling the Authentication API directly to use a refresh token. Is there anything wrong with doing that?

Nothing wrong with that at all. There is a method on the Authentication API class you can use directly for that. Everything in `Auth0` is meant to be a "helper" for common scenarios. Using the Management and Authentication classes directly is an expected use case as well.

**Comment by unoscar** [comment]
Hi Guys, is there a fix or implementation for this issue? I changed the refresh token method to the `refresh_token` function on the Authentication API directly and I am getting the correct new tokens. But, when I am trying to save them to the current session using `$auth0->setAccessToken()` and `$auth0->setIdToken` I am still getting the nonce error 

`Nonce value not found in application store`

**Comment by joshcanhelp** [comment]
@unoscar - Apologies for the delay here. We're taking a look now.

**Comment by borishcs** [comment]
I have the same problem, my app returns "Nonce value not found in application store"

**Comment by joshcanhelp** [comment]
@borishcs - Thanks for the report here. Is this when using a refresh tokens or some other way? We're addressing the refresh token use case here but if there is another place where this is happening and you think it shouldn't, reproduction steps/code would be helpful.

**Comment by joshcanhelp** [comment]
For everyone else ... I appreciate your patience on this. While skipping the nonce check is not a technically hard thing to do, we don't want to leave the door open to just turn off nonce checking. Also, we want to make sure the tests more accurately reflect how that method is used. You can see progress on the PR linked above 👆
