### ISSUE TITLE
TypeError when using cookies as storage

### ISSUE THREAD

**Issue by mnapoli** [auth0/auth0-PHP#436]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Configuring Auth0 to use the `CookieStore` throws exceptions:

```
Uncaught TypeError: Argument 2 passed to Auth0\SDK\Store\CookieStore::setCookie() must be of the type string, array given
```

### Reproduction

Here is the configuration:

```php
$auth0 = new Auth0([
            'domain' => 'madyams.eu.auth0.com',
            'client_id' => getenv('AUTH0_CLIENT_ID'),
            'client_secret' => getenv('AUTH0_CLIENT_SECRET'),
            'redirect_uri' => getenv('AUTH0_REDIRECT_URI'),
            'scope' => 'openid profile email',
            'store' => new CookieStore([
                'expiration' => 60 * 24 * 30,
            ]),
        ]);
```

The exception happens on `$auth0->getUser()` after logging in.

Stack trace : 

![CleanShot 2020-05-06 at 19 46 50](https://user-images.githubusercontent.com/720328/81210572-5e868600-8fd2-11ea-8b37-fce6bc959c04.png)

The error sounds logical: the `Auth0` class tries to store the user into the store. The user is an `array`. The `CookieStore` only accepts `string` as values.

Shouldn't the array be serialized (to JSON, or to anything) before being stored?

### Environment

> Please provide the following:

- **Version of this library used:** 7.2.0
- **Version of the platform or framework used, if applicable:** No framework
- **Other relevant versions (language, server software, OS, browser):** PHP 7.4
- **Other modules/plugins/libraries that might be involved:**

**Comment by joshcanhelp** [comment]
@mnapoli - Appreciate the thorough report here and apologies for the delay. I see how those types are not matching up to create this issue. It wasn't really our intension for user data to be store plainly in a cookie but if it's not sensitive data then I don't see a big problem with it. At the very least, we shouldn't be stopping you with a `TypeError` 😃 

The problem here, though, is that Session is capable of storing types other than strings but Cookies are not. If we stringify in `Auth0`, that's a breaking change for anyone using Session and accessing directly. 

It seems like the right place to do this conversion is in `\Auth0\SDK\Store\CookieStore::set()` but if we convert it, we'd need to convert it back before returning, otherwise we break the contract with the caller. 

Another possible option is to add a flag in `Auth0` to stringify the profile, which would then allow other storage strategies to safely store the profile. We could maybe turn that on automatically if the `CookieStore` is used. 

Any opinion one way or the other?

**Comment by mnapoli** [comment]
TBH I think adding an option for users is confusing. Using that library is already hard enough I would say. So automatically converting back and forth would make sense, because as a user I would expect things to "just work".

Regarding my project, I ended up implementing another storage. The fact that the native storages are impacting global state (using global variables) make them hardly compatible with classic PHP frameworks.

Here is the storage I created. It is a PSR-15 middleware:

```php
/**
 * @see \Auth0\SDK\CookieStore
 */
class Psr7CookieStore implements StoreInterface, MiddlewareInterface
{
    private const PREFIX = 'auth0_';

    private array $requestCookies = [];
    /** @var SetCookie[] */
    private array $setCookies = [];

    private LoggerInterface $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $this->requestCookies = $request->getCookieParams();

        $response = $handler->handle($request);

        foreach ($this->setCookies as $setCookie) {
            $response = FigResponseCookies::set($response, $setCookie);
        }

        return $response;
    }

    public function set(string $key, $value) : void
    {
        $value = json_encode($value, JSON_THROW_ON_ERROR, 512);
        $this->logger->info("Set $key=$value");

        $this->setCookies[] = SetCookie::create(self::PREFIX . $key, $value)
            ->rememberForever()
            ->withSameSite(SameSite::strict());
    }

    public function get(string $key, $default = null)
    {
        $cookieValue = $this->requestCookies[self::PREFIX . $key] ?? null;
        if ($cookieValue) {
            $cookieValue = json_decode($cookieValue, true, 512, JSON_THROW_ON_ERROR);
        }

        return $cookieValue ?? $default;
    }

    public function delete(string $key) : void
    {
        $this->logger->info("Delete $key");

        $this->setCookies[] = SetCookie::create(self::PREFIX . $key, null);
    }
}
```

**Comment by joshcanhelp** [comment]
> TBH I think adding an option for users is confusing ... as a user I would expect things to "just work".

I totally agree. But we can't always convert it (breaking change) and we want to account for storage strategies in the future that might need this same conversion. 

> Using that library is already hard enough I would say.

If you have any feedback about this, we're happy to hear it. We want our SDKs to be as simple to use by default as possible. Identity is complex enough as it is!

> The fact that the native storages are impacting global state (using global variables) make them hardly compatible with classic PHP frameworks.

Agreed but PHP session are simple to get working right away. The Laravel package takes advantage of the Laravel session management and that might be an option for other frameworks as well. 

> Here is the storage I created

Appreciate you sharing that here. It looks like this is only capable for arrays/objects as a string value would return `null`. I assume you're just using this in the user storage and not for nonce/state, correct?

**Comment by mnapoli** [comment]
> But we can't always convert it (breaking change) and we want to account for storage strategies in the future that might need this same conversion.

Yep, I understand the breaking change.
Maybe it could be worth detecting if the value is an array: if it is, it could be JSON-encoded. If not, it would be kept as-is.

However, that is not simple when decoding: how do you check if a value is encoded JSON or not 🤔 

> It looks like this is only capable for arrays/objects as a string value would return null. I assume you're just using this in the user storage and not for nonce/state, correct?

This is how I used it:

```php
       $auth0 = new Auth0([
            'domain' => '...',
            'client_id' => getenv('AUTH0_CLIENT_ID'),
            'client_secret' => getenv('AUTH0_CLIENT_SECRET'),
            'redirect_uri' => getenv('AUTH0_REDIRECT_URI'),
            'scope' => 'openid profile email',
            'store' => $container->get(Psr7CookieStore::class),
        ])
```

Hopefully that answers your question, because I don't know how to answer it 😅 I would say I use `json_encode` for all values, so string values should be stored as well, but I might be missing something.

**Comment by joshcanhelp** [comment]
@mnapoli - Appreciate the feedback here! Your solution is probably a suitable work-around for now until we can figure out the best way to make the core storage work in this case.

**Comment by evansims** [comment]
This is an interesting proposal, and I appreciate the thoughtful discussion shared here, as well as the example code. Thanks very much for your work here. We'll continue thinking on how we could expand the core storage strategy for the library.

At the moment I feel like integrating the proposed functionality into the cookie store sits a bit outside our intentions. Doing so would present potential breaking changes and/or introduce complexity that at this point doesn't really make sense. However, the example code you provided offers a perfect solution for others who need a solution like this, and we will gladly point others to this issue as a reference for addressing this.
