### ISSUE TITLE
Multiple audiences/issuers gone

### ISSUE THREAD

**Issue by natepage** [auth0/auth0-PHP#437]
The previous version of the SDK (using the JWTVerifier) allowed applications to verify id tokens against multiple audiences and issuers.

Looking at the new version of the SDK, the TokenVerifier now accepts audience and issuer as string only.

Is that intended? If yes why?

Thanks

**Comment by joshcanhelp** [comment]
@natepage - ID tokens should have a single issuer, the identity provider (Auth0), and a single audience, your application. What's the use case for having more than one for either?

**Comment by natepage** [comment]
@joshcanhelp thanks for the reply, our use case is actually only about the audience.

We have multiple APIs, each of these has an API in Auth0 so an audience and they're all configuring to accept id tokens only for their audience.

Then we have another API to centralize the management of our users, the other APIs and the access policies (who can access which API).

All that put together with a frontend using silent auth to switch from using one API to another.

In each frontend app we have a header menu giving the user the list of apps he has access to, this list is dynamically fetched from the centralized API.

So the centralized API can accept id tokens from each of the other APIs it knows about using multiple audiences.

**Comment by joshcanhelp** [comment]
Thanks for writing this all out. My advice here has to be general as I'm not going to be able to review your complete architecture. But it sounds like you're using ID tokens incorrectly.

> We have multiple APIs, each of these has an API in Auth0 so an audience and they're all configuring to accept id tokens only for their audience.

These APIs should be accepting access tokens generated for them with the API audience, not ID tokens with the audience of the applications sending them. 

https://auth0.com/docs/tokens/guides/get-access-tokens

> Then we have another API to centralize the management of our users, the other APIs and the access policies (who can access which API).

I suspect this probably should be running the same way, requesting access tokens for this API.

> So the centralized API can accept id tokens from each of the other APIs it knows about using multiple audiences.

ID tokens should stop at the application, not sent to other APIs. The audience in the token is a hint to that. 

https://auth0.com/docs/tokens

---

Judging by the amount of feedback on this issue, there might be a lot of folks following this same pattern. If anyone else has a different scenario that the single audience/issuer breaks, we'd definitely appreciate the feedback.

**Comment by natepage** [comment]
@joshcanhelp Thank you for your reply. So yes it looks like we're not using Access Tokens the recommended way 😄 

As I can see in the article you've linked, the example about Access Token has multiple audiences in the token. We've basically done it the other way around by setting only a single audience on the token and make our centralised API validate against multiple audiences.

It is probably not the recommended way to use Access Tokens but it works very well for us, would it be possible to meet in the middle? By default the SDK supports only one audience but it is built in a way that people can easily override this logic if needed?

As I can see the signature validation has already been extracted to its own class, maybe we could do the same for audience and issuer so it makes extending the logic easier?

**Comment by natepage** [comment]
@joshcanhelp As an idea, we could implement setters on `TokenVerifier`:

- `setAudienceValidator(AudienceValidatorInterface $audienceValidator)`
- `setIssuerValidator(IssuerValidatorInterface $issuerValidator)`

Using setters will allow it to be BC compatible, because in the `verify` we check if those validators have been set, if not then we use a default implementation that basically just do what is done right now in `TokenVerifier` directly.

If you're not against the idea, I'm happy to create a PR for it.

**Comment by evansims** [comment]
Hey everyone; thanks for your feedback and insights on this. I think there are enough fair arguments on this one (and it's popped up on some of our other SDKs as a request as well) to suggest it should be something developers can opt into as they deem appropriate. I've currently slated this for reintroduction in the next major release, 8.0. I'll update this thread when the release happens. Thanks!
