### ISSUE TITLE
Guzzle exception message gets truncated

### ISSUE THREAD

**Issue by healerz** [auth0/auth0-PHP#440]
### Description
If an API error occurs, the error details are truncated in the guzzle client exception. Which is known but, as far as I understand, will not be addressed by guzzle (https://github.com/guzzle/guzzle/issues/2185).

I do know, that the full response is accessible through `$e->getResponse()->getBody()->getContents()`, but I'd prefer that the auth0 library provides a non truncated exception message. Either through re-creating the guzzle ClientException or by throwing an Auth0Client exception containing the full error message.

### Reproduction
Any auth0 request which will end in an error. Then check out the `GuzzleHttp\\Exception\\ClientException::$message`.

### Remark
Personally, I'd prefer to inject a PSR-18 compatible HTTP client into the Auth0 client.

### Environment
auth0/auth0-php: 7.2.0
guzzlehttp/guzzle: 6.5.5

**Comment by evansims** [comment]
Hey @healerz 👋  Sorry for the delay in responding to this. I totally agree this isn't ideal. I like your idea of being able to plug a PSR-18 compatible HTTP client in there. I'll investigate our options here and see what we can do.

**Comment by evansims** [comment]
Hey again @healerz 👋 Just an update on this, going forward my plans for the next major release of the library is to support PSR-18 for passing custom implementations at SDK initialization. Closing this as it will be resolved by this forthcoming change.

**Comment by healerz** [comment]
Hi @evansims thanks a lot for your answer and i'm looking forward to the upcoming change to be able to inject a PSR compatible http client 👍

**Comment by healerz** [comment]
Hi @evansims 
Just wanted to thank you for the version 8 major release. We're looking forward to upgrading it on our end.

**Comment by evansims** [comment]
Thanks very much @healerz, I hope the upgrade goes smoothly for you! Please reach out to me if you encounter any issues or have questions in the process.
