### ISSUE TITLE
IDTokenVerifier verify always fail with valid token because compare Azp with audience definitely always return false

### ISSUE THREAD

**Issue by faizalmansor** [auth0/auth0-PHP#442]
On line 80-98: 
https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/Tokens/IdTokenVerifier.php

```php
/*
 * Authorized party check
 */
$tokenAud = $verifiedToken['aud'] ?? null;

if (is_array($tokenAud) && count($tokenAud) > 1) {
    $tokenAzp = $verifiedToken['azp'] ?? null;

    if (! $tokenAzp || ! is_string($tokenAzp)) {
        throw new InvalidTokenException(
            'Authorized Party (azp) claim must be a string present in the ID token when Audience (aud) claim has multiple values'
        );
    }

    if ($tokenAzp !== $this->audience) {
        throw new InvalidTokenException( sprintf(
            'Authorized Party (azp) claim mismatch in the ID token; expected "%s", found "%s"',
            $this->audience,
            $tokenAzp
        ) );
    }
}
```

Why is `$tokenAzp` compared with `$this->audience` ? Should be an attribute of `$this->azp` if need to compare for Authorized party. Or is there something wrong in my understanding?

**Comment by joshcanhelp** [comment]
If there are multiple audiences then we should have an `azp` and if we do, then it should match the audience indicated by the application.

Are you getting an error you didn't expect? If so, can you share your config?

**Comment by faizalmansor** [comment]
When I instantiate IdTokenVerifier like so,
```
$token_verifier = new IdTokenVerifier(
            $token_issuer,
            $valid_audiences,
            $signature_verifier
);
```
I provide different data for `$token_issuer` & `$valid_audiences`. So when it goes through the IdTokenVerifier it check this (line 91 of https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/Tokens/IdTokenVerifier.php):
```
 if ($tokenAzp !== $this->audience) {
```
While in the parent class it check this (line 120 - 130 of https://github.com/auth0/auth0-PHP/blob/eb04b2a05118383e6212914cf3316082c5362bc5/src/Helpers/Tokens/TokenVerifier.php#L14)
```
} else if (is_string($tokenAud) && $tokenAud !== $this->audience) {
```
So I got those 2 errors back and forth no matter which way I put the arguments in. At one point it check Azp with audience (this is the one that doesn't make sense) while in the other part it check audience with audience. Is there something wrong in my usage? Thanks

**Comment by evansims** [comment]
Unfortunately, I'm not able to recreate the issue being reported here on my end. Notably, however, this behavior will be getting reworked in the next SDK major.
