### ISSUE TITLE
Replacement or option for JWT Access Token verify & decode

### ISSUE THREAD

**Issue by cpcadmin** [auth0/auth0-PHP#445]
In the old version we could easily verify and decode an access token as we are using API features only and will never receive and ID token nor want to retrieve one every time an API call is made.  Why not add a simple decodeAccessToken to the new Auth0 service that sends in the proper application audience rather than the clientId as configured in php?  Or am I missing something?

**Comment by joshcanhelp** [comment]
Would the `TokenVerifier` class work for what you need?

https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/Tokens/TokenVerifier.php

This documentation page covers the `IdTokenVerifier` class but much of it is the same:

https://auth0.com/docs/libraries/auth0-php/validating-jwts-with-auth0-php

**Comment by cpcadmin** [comment]
Not sure why the status changed here.  I left an open question that is still unanswered.  Thanks.

**Comment by evansims** [comment]
Hey there! 👋 Thanks for bringing this to our attention. As this appears to be a compatibility issue specifically with the symphony module, we'll track this over on that repo. It looks like you've already opened a ticket there, so we'll continue it here when we have an update for you: https://github.com/auth0/jwt-auth-bundle/issues/103
