### ISSUE TITLE
Can't verify access tokens

### ISSUE THREAD

**Issue by ppaulis** [auth0/auth0-PHP#460]
Hi!

I'm currently having some trouble verifying access tokens. I'm using the `auth0/auth0-angular` package in a Single page application, and using it's interceptor I'm sending an `Authorization` header like this:
```
Authorization: Bearer 1irGWfRtxxxxxxxxxxxxxxxxxxxxxxxx
```
On the API side, I can decode and verify *ID* tokens like this:
```
$jwksFetcher = new JWKFetcher(
    null,
    ['base_uri' => 'https://xxxxxxxxxxxx.eu.auth0.com/.well-known/jwks.json']
);
$sigVerifier   = new AsymmetricVerifier($jwksFetcher);
$tokenVerifier = new IdTokenVerifier(
    'https://xxxxxxxxxxxx.eu.auth0.com/',
    '<audience>',
    $sigVerifier
);
$tokenInfo = $tokenVerifier->verify($token);
```
But afaik I shouldn't send ID tokens to the API and use *Access* tokens instead (the Angular lib is indeed sending the access token, and not the ID token). So, I'm trying to use the _TokenVerifier_ instead of the _IdTokenVerifier_:
```
$jwksFetcher = new JWKFetcher(
    null,
    ['base_uri' => 'https://xxxxxxxxxxxx.eu.auth0.com/.well-known/jwks.json']
);
$sigVerifier   = new AsymmetricVerifier($jwksFetcher);
$tokenVerifier = new TokenVerifier(
    'https://xxxxxxxxxxxx.eu.auth0.com/',
    '<audience>',
    $sigVerifier
);
$tokenInfo = $tokenVerifier->verify($token);
```
But the only thing I get here, is an Exception with the message :
```
ID token could not be decoded
```
I'm quite sure, that I misunderstood something here... is there anyone that can enlighten me...?

(auth0-php version 7.4.0)

Thanks!
Pascal

**Comment by ppaulis** [comment]
Problem solved. There was an audience parameter missing in the SPA:
```
AuthModule.forRoot({
      domain: 'xxxxxxxxxxxxxxx.auth0.com',
      clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      audience: '<audience missing>',
      redirectUri: window.location.origin,
      httpInterceptor: {
        allowedList: [
          ....
        ],
      },
    }),
```

**Comment by evansims** [comment]
Glad you got it sorted Pascal, thanks for the update!
