### ISSUE TITLE
Unable to set user metadata

### ISSUE THREAD

**Issue by bruno-barros** [auth0/auth0-PHP#466]
### Describe the problem

I'm trying to set `user_metadata`, but got error `{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object but found type null'.","errorCode":"invalid_body"}`
I'm able to get data from API.

### What was the expected behavior?

Get success update response.

### Reproduction

I'm using the development token.

```
$mgmt_api = new Management( 'long string here', 'mytenant.auth0.com' );
$mgmt_api->users()->update('auth0|someID', [
       'user_metadata' => [
           'idCustom' => 123
       ]
   ])
```

### Environment

Some dependencies:
"guzzlehttp/guzzle": "6.3.*",
"auth0/auth0-php": "^7.5"

**Comment by evansims** [comment]
Hey @bruno-barros 👋 Sorry to hear you're hitting some trouble with this. I haven't been able to reproduce this error on my end quite yet — however, all my tests are currently configured to use Guzzle 7, so I need to do some further work to match your environment. Could you tell me what PHP version you're seeing this on, please?

**Comment by bruno-barros** [comment]
Hi @evansims 
I'm running on PHP 7.3.
I already had problems with guzzle's version. On 7 the content use the "form_params" key, but before 7 it's "body".
On a project I worked I did this:
```
if (defined('GuzzleHttp\Client::VERSION') && version_compare(Client::VERSION, '6', '<='))
{
    $clientParams['body'] = $data;
}
else
{
    $clientParams['form_params'] = $data;
}
```
I can try with the Guzzle 7 to see if it's the problem here.

**Comment by bruno-barros** [comment]
@evansims just to let you know.
I tried with guzzle 7 and it works. Will you hunt around it?

**Comment by evansims** [comment]
Hey @bruno-barros 👋 Sorry for the delay, and thanks for your help in tracking this down to an issue with our Guzzle 6 support! It's regrettable that went unnoticed till now. As it so happens, our next release of the SDK will phase out Guzzle 6 support out of necessity to allow for PHP 8 compatibility, so this issue will be resolved inherently through that change.
