### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by decima** [auth0/auth0-PHP#469]
### Describe the problem you'd like to have solved

Enable support for PHP 8.0

### Describe the ideal solution

Changing composer.json dependency

## Alternatives and current work-arounds

none

### Additional information, if any

A lot of projects have made the move, hoping you'll do it too :-)

**Comment by evansims** [comment]
Hey @decima 👋  Thanks for raising this issue! Been hard at work on that front, and you'll be pleased to know we have a PR pending to get support in for the next release. #467

**Comment by decima** [comment]
That's a good news @evansims ! we are waiting for it to know if we start our project in php 7.4 or 8 so we're exciting and waiting for it ! :)

**Comment by evansims** [comment]
Thanks for your patience on this! PHP 8.0 support is now available with [SDK 7.6](https://github.com/auth0/auth0-PHP/releases/tag/7.6.0) 🎉

**Comment by decima** [comment]
Thanks a lot :)
