### ISSUE TITLE
Update to use v3.0 of firebase/php-jwt

### ISSUE THREAD

**Issue by jeffisfast** [auth0/auth0-PHP#47]
Hello,

The current library is using an old version of the firebase/php-jwt library, which is now out of date.  Can you update your software to use the current version (v3.0)?  

Here is output from composer that shows the problem when I try to include the "firebase/php-jwt":"~3.0":

$ ./composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for auth0/auth0-php ~2.0 -> satisfiable by auth0/auth0-php[2.0.0].
    - auth0/auth0-php 2.0.0 requires firebase/php-jwt ~2.2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by glena** [comment]
I am releasing 2.1.0 with this change.
Thanks :)
