### ISSUE TITLE
Users getAll has mistake of pagination

### ISSUE THREAD

**Issue by nfq-phung** [auth0/auth0-PHP#475]
<img width="846" alt="Screen Shot 2021-01-22 at 9 34 34 AM" src="https://user-images.githubusercontent.com/51575007/105438188-0fce6880-5c95-11eb-929e-05f9c7a9f2e1.png">

It should be:

```
 $params = $this->normalizePagination($params, $page, $per_page);
 $params = $this->normalizeIncludeTotals($params);


```

**Comment by evansims** [comment]
Hey @nfq-phung 👋 Good catch, thanks for raising this. I'll get a fix merged shortly.
