### ISSUE TITLE
Allow passing client id to tickets api (password change)

### ISSUE THREAD

**Issue by dmason30** [auth0/auth0-PHP#480]
### Describe the problem you'd like to have solved

The tickets api since the new universal login has accepted a client_id yet this package does not currently support it. 

The client_id cannot be used in conjunction with return_url as it will result in an error.

It is a bit of an inconvenience that we can no longer use return_url in the new universal login and there is no dynamic replacement as it relies on default login urls one per client which is not great when you want to use the same client on many sites (e.g. SSO). 

### Describe the ideal solution

Add new method or arg to existing `createPaswordChangeTicket*` methods. 
```php
$api->tickets()
    ->createPasswordChangeTicketByClient($userId, $clientId);
```

## Alternatives and current work-arounds

```php
$api->tickets()
    ->getApiClient()
    ->method('post')
    ->addPath('tickets', 'password-change')
    ->withBody(json_encode([
        'user_id' => $id,
        'client_id' => $this->getClientId(),
    ]))
    ->call()
```

**Comment by evansims** [comment]
Hey, @dmason30 👋

Good catch on this, and thanks for making me aware! I'll address this shortly

**Comment by evansims** [comment]
Passing `client_id` is now supported as of today's 7.7.0 release, thanks!
