### ISSUE TITLE
auth0/php-jwt conflicts with lcobucci/jwt

### ISSUE THREAD

**Issue by pmccarren** [auth0/auth0-PHP#486]
Hello,

I am working to setup auth0-php in my application, however am encountering composer conflicts. I intend to migrate my user base from [laravel/passport](https://github.com/laravel/passport) to Auth0.

Both the `auth0/php-jwt` and `lcobucci/jwt` repos define the `Lcobucci\JWT\` namespace, which causes composer to complain, and errors to be encountered while instantiating classes.

`laravel-passport` requires  `lcobucci/jwt ^3.4 | ^4.x`, which is not compatible with auth0's [fork](https://github.com/auth0/auth0-PHP/blob/aea991b2e39b284df905f1b28c19aab3d0511d15/composer.json#L17).

Can you please help me understand the necessity of the auth0 fork?

**Comment by evansims** [comment]
Hi @pmccarren 👋 `auth0/auth0-PHP 3.3.4` is a drop-in replacement for `lcobucci/jwt 3.3.3` with added PHP 8 support, as the author didn't want to merge PHP 8 compatibility in the upstream package to the 3.X branch. The 4.X branch of `lcobucci/jwt`, and later versions of the 3.X branch, introduce a new API which will require breaking changes in our SDK to adapt to so it's unfortunately not as simple as a dependency change, and thus our fork. The next major release of this SDK will resolve this, but in the meantime, if you need to use the JWT library independent of our SDK, you'll need to continue using the 3.3.3-compatible API and our fork as a drop-in replacement.

**Comment by marko-ilic** [comment]
Is it possible to change namespaces in auth0/php-jwt to avoid conflicts with lcobucci/jwt?
