### ISSUE TITLE
[7.9] Make Auth0\SDK\Auth0::getState a public method

### ISSUE THREAD

**Issue by jamescrowley** [auth0/auth0-PHP#495]
### Describe the problem you'd like to have solved

I'm intending to store the full redirect variable in the session, and was intending to use the `state` nonce as the key, based on your guidance here: https://auth0.com/docs/protocols/state-parameters.

I could be mis-understanding here, but the PHP library currently:
* allows you to send a $state variable when calling login()
* allows you to generate a sensible value for the $state variable, using getNonce()
* validates that the $state variable matches in the callback exchange, even when user supplied

And yet there's no way to fetch the state variable back again to the consuming code, without extending the auth0 class, due to getState() being protected. 

Is there any reason for this?

### Describe the ideal solution

Make getState() public, if there are no unintended problems with this that I'm missing.

**Comment by evansims** [comment]
Hey, @jamescrowley 👋 I think that's a fair suggestion, I don't see any particular reason why that couldn't be made public. I'll work on getting that change incorporated.

**Comment by evansims** [comment]
Hey again, @jamescrowley 👋 This change has been merged and will be part of the 7.9 release. Thanks for your suggestion.

**Comment by jamescrowley** [comment]
Thanks @evansims
