### ISSUE TITLE
Encode Management API parameters before sending API requests

### ISSUE THREAD

**Issue by FabianRahm** [auth0/auth0-PHP#497]
As per https://community.auth0.com/t/search-users-with-sign-in-e-mail-addess-via-mgmt-api-and-getall/61550 I can't query for users with the PHP SDK having + addresses (e.g. foo+bar@domain.tld).

The SDK is not encoding query parameter values properly before calling the endpoint.

`        return $mgmtApi->users()->getAll([
            'q' => strtolower($email)
        ]);`

**Comment by evansims** [comment]
Hey, @FabianRahm! 👋 Thanks for the suggestion. That's a good catch, we should be handling that on the library side rather than requiring apps to do it manually. As this would potentially be a breaking change I'll slot it in for 8.0 work. Thanks for the heads up.

**Comment by FabianRahm** [comment]
Thanks for taking this up. A good reference for clean HTTP requests is the Stripe PHP package over at https://github.com/stripe/stripe-php.

**Comment by evansims** [comment]
Hey again @FabianRahm 👋  Just to update you, this has been resolved [with the forthcoming 8.0 branch](https://github.com/auth0/auth0-PHP/tree/8.x) which should be seeing release at the end of June if all goes as planned. Thanks for bringing this our attention! I'll go ahead and close this as it's been addressed with that release 👍

**Comment by FabianRahm** [comment]
Excellent news, thank you!
