### ISSUE TITLE
[SDK-2595] Decouple from Guzzle

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#502]
Hey. Guzzle maintainer here. 

Back in 2017 I was working to decouple this library from Guzzle. That was the unreleased version 6. 

I see that this library is throwing some guzzle exceptions and provide some "guzzle options". But most "Guzzle things" are in the `RequestBuilder`. 

There are a few issues with the Guzzle implementation: 
1. It does not support guzzlehttp/psr-7:2.0
2. It creates a new `Client` at each request which prevents guzzle to resuse sockets and is generally much slower. 
3. Every user is required to use Guzzle. PSR-18 is tailor made for this use case. 

I suggest that we should work towards using PSR-18 (Supported in Guzzle 7) and PSR-17. If the user does not provide a client or request factories, we can fallback to use Guzzle. 

This means, that for the user that do not care about decoupling from guzzle, the only change they need to do in to include `guzzlehttp/guzzle`  when they first install the library. 

```
composer require auth0/auth0-php guzzlehttp/guzzle
```

**Comment by evansims** [comment]
Hey @Nyholm! 👋 Funny you should mention that, that's actually exactly what I'm working on this week, adding PSR-18 and PSR-17 support into the 8.x branch. It's in the works!

**Comment by Nyholm** [comment]
That is great news!

Let me know if you need any help or review.

**Comment by Nyholm** [comment]
Wohoo. Thank you for https://github.com/auth0/auth0-PHP/commit/9564622151f37d02f24560b6fad1e76de8298050

I'll start updating the [Symfony bundle](https://github.com/Happyr/auth0-bundle) next week to support 8 instead of 6 alpha. I know it is super early. But I would like to encourage you to use alpha releases for 8.0. 

(Im not saying that "now" is the correct time to do them, but do it whenever you think "I believe this could work")

**Comment by evansims** [comment]
Hey @Nyholm thanks! Have a few more changes in flight to this before I wanted to ping you about a review, but if you get a chance to take a look, I'd love to hear if you think I'm taking the right approach on this, or if you have any feedback on how I could improve this

**Comment by evansims** [comment]
Going to close this one as it's been incorporated into the 8.x branch pending release later this month. Would still love any feedback you have on refining the implementation if you get time! Can just continue the discussion here and re-open this ticket if we decide improvements should be made. Thanks again

**Comment by Nyholm** [comment]
There is now an excellent time for an alpha release. That allows me to update the Auth0 bundle and allows me to try things out in real apps. 

I will schedule some work on this this week (or weekend).

**Comment by evansims** [comment]
Very much appreciated! Just finalizing our internal security review on Auth0's end and then I'll get a proper alpha up, just need to dot all our i's and all that. 👍  I'll update here when it's officially gone alpha

**Comment by Nyholm** [comment]
I've done a review. Great job. 

I've added a few PRs and one issue. The symfony bundle is ready for 8.0 after these things are resolved.
