### ISSUE TITLE
[8.x] Cache Management access token

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#513]
When you create a new `Management` without an access token, it will use `Authentication` to get a new access token. This is great. However, we should cache that new access token. If not, each request on the customers website will lead to a request to auth0 to fetch the access token. 

This will also make sense for the Auth0Bundle, ie it does not have to manage that cache.

**Comment by evansims** [comment]
Hey, @Nyholm 👋 Good suggestion! I've added a `managementTokenCache`option to the configuration that accepts a PSR-6 instance for this use. Thanks for all the great feedback and contributions on this.

**Comment by Nyholm** [comment]
Great. Thank you.
