### ISSUE TITLE
[8.x] No IDE autocompletion for Management

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#520]
One should avoid magic methods. 

I suggest replacing `Management::__call()` with real implementation. Maybe add these real implementation in an `@internal` trait if we don't want to "pollute" the nice looks of the class. 

If we really really really dont want to use real implementation, I suggest adding `@Method` annotations on the class.

**Comment by evansims** [comment]
Hey @Nyholm 👋 I'm preferring the magic method for this since it reduces the redundancy of the class, but I definitely agree the `@method` calls should be there, just an oversight. I'll add that, thanks!

**Comment by Nyholm** [comment]
Hm. Im not sure it *reduces* the redundancy, it just hides in in a magic way. 

But the `@method` will make sure IDEs and static analysers properly can inspect and understand the code.

**Comment by evansims** [comment]
Fixed on the dev branch, will be part of the next beta release! 👍 Thanks for the heads up!

**Comment by Nyholm** [comment]
Thank you
