### ISSUE TITLE
Use API classes as lazy Container services

### ISSUE THREAD

**Issue by amenophis** [auth0/auth0-PHP#527]
### Describe the problem you'd like to have solved
I'm trying to use https://github.com/Happyr/auth0-bundle to implement auth0 authentication in a symfony application.
The bundle define services for SDK Classes (`Auth0\SDK\Auth0`, `Auth0\SDK\API\Management` and `Auth0\SDK\API\Authentication`).
These services are declared as lazy because they do some HTTP request in the constructor.
This is a very big issue because in each requets done on the application where one of the services is injected, HTTP requests are made even if the service is not used.

The symfony lazy behavior is based on the `symfony/proxy-manager-bridge` component which create proxy classes for service, and instanciate the class on the first usage. Symfony simply ignore the lazy declaration if the component is not installed.

The issue is that classes in the SDK are declared final, so they cannot be extended by the proxy component.
I opened an issue on the bundle here: https://github.com/Happyr/auth0-bundle/issues/42

### Describe the ideal solution

We can think about 2 solutions:
  * Remove the final keyword to allow class extending by the proxy component, which is not the better way.
  * Move constructor logic inside an init function and call it inside all classes public methods. The constructor must keep only argument storage logic.

**Comment by Nyholm** [comment]
Thank you for this issue. 

Your second suggestion is the "more correct" one. I think that one should be implemented. That will allow the bundle to remove the workaround with lazy services.

**Comment by evansims** [comment]
Hey @amenophis 👋 Thanks for your suggestion. I don't think removing the final keyword is a path we'd want to go down.

The only class that potentially sends an HTTP request from the constructor is `Auth0\SDK\API\Management`, depending on what information is passed to the SDK during configuration, the others simply create instances of `Auth0\SDK\Utility\HttpClient` for use later, but they aren't actually invoked from the constructors, so no requests are sent.

That said, I think the suggestion is reasonable! I suppose we shouldn't really be creating an instance before it's actually necessary, anyway. Let me draft up a PR for this tomorrow, and we'll see how it looks.

**Comment by Nyholm** [comment]
Awesome news. Thank you

**Comment by evansims** [comment]
Hey @Nyholm and @amenophis 👋  I have a draft PR up that refactors the constructors on two of those classes. The core class, `Auth0\SDK\Auth0`, doesn't appear to create anything that could or should be lazy loaded. Can you confirm that? Let me know if these changes address your needs adequately.

**Comment by evansims** [comment]
Hey @amenophis 👋  These changes were approved and merged. I'm going to cut a new beta release in the next day or two that will include these changes, just want to wrap up one other thing I'd like to sneak in there first. Hang it.

**Comment by evansims** [comment]
👋  BETA2 is now available, which includes this change
