### ISSUE TITLE
GetCredentials returns a null session unless you also getUser

### ISSUE THREAD

**Issue by Webbeh** [auth0/auth0-PHP#537]
### SDK Version

8.0.0-BETA1

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

While trying out the new API for a new web app, following the usage instructions here on this github, I encounter a small bug with `getCredentials()`.

Basically, `$session = $auth0->getCredentials();` always returns null unless I also call `$auth0->getUser();` before it.

Further down in "How to reproduce", if you remove the `var_dump($auth0->getUser());` line, $session will then always be null and, on this case, it will do a redirect loop between auth0's `/authorize` endpoint and the page itself.

Lastly, if you move the `getUser()` call AFTER the `getCredentials()` call, the app will call the `/authorize` endpoint one more time before actually displaying anything, confirming that the `getCredentials()` was null on the first iteration.

### How can we reproduce this issue?

- `composer require guzzlehttp/guzzle`
- Follow the instructions on this github's README for installation of Auth0 through composer.
- Paste the code down here in `auth0.php`
- In index.php, `require("auth0.php");`

```php
<?php
session_start();
require_once __DIR__.'/vendor/autoload.php';

use Auth0\SDK\Auth0;
use Auth0\SDK\Configuration\SdkConfiguration;
use Auth0\SDK\Utility\HttpResponse;
use Buzz\Client\MultiCurl;
use Nyholm\Psr7\Factory\Psr17Factory;

$Psr17Library = new Psr17Factory();
$Psr18Library = new MultiCurl($Psr17Library);

$auth0_configuration = new SdkConfiguration(
    httpClient: $Psr18Library,
    httpRequestFactory: $Psr17Library,
    httpResponseFactory: $Psr17Library,
    httpStreamFactory: $Psr17Library,
    domain: '<redacted>.eu.auth0.com',
    clientId: '<redacted>',
    clientSecret: '<redacted>',
    cookieSecret: "<redacted>",
    redirectUri: "<redacted>",
    queryUserInfo: true
);

$auth0 = new Auth0($auth0_configuration);

var_dump($auth0->getUser());
$session = $auth0->getCredentials();
var_dump($session);


if($session===null)
{
    $loc = $auth0->login();
    header("Location: ".$loc);
    exit();
}
```

**Comment by evansims** [comment]
Hi @Webbeh 👋 Let me look into this and get back to you

**Comment by evansims** [comment]
Hey again, @Webbeh 👋 Thanks for your patience.

Have you authenticated (and therefor have a session present on the device) before calling `getCredentials`? `getCredentials` will return `null` unless it finds an available session. By itself, it won't try to initiate a code exchange (unlike `getUser()`.)

For example, [looking at the PHP quickstart](https://github.com/auth0-samples/auth0-php-web-app/blob/8.x/src):
- [An index route checks `getCredentials` to determine whether to show the user as logged in or not.](https://github.com/auth0-samples/auth0-php-web-app/blob/8.x/src/Application.php#L179) (`Auth0->getCredentials()`)
- [A callback route handles the code exchange after the user returns from authenticating with Auth0](https://github.com/auth0-samples/auth0-php-web-app/blob/8.x/src/Application.php#L210), so the local session on the end-user's device can be configured. (`Auth0->exchange()`)
- [A login route handles starting the authentication flow](https://github.com/auth0-samples/auth0-php-web-app/blob/8.x/src/Application.php#L233) (`Auth0->login()`)
- [A logout route handles clear the local session and clears Auth0's remote session](https://github.com/auth0-samples/auth0-php-web-app/blob/8.x/src/Application.php#L251) (`Auth0->logout`)

(Unrelated side note, you probably won't need to enable `getQueryUserInfo` in most cases.)

**Comment by Webbeh** [comment]
Thanks.

Maybe it would be a good thing to update the README for `getUser()` instead of `getCredentials()`.

I tried to follow the README for a quick start and it led me to this issue.

Closing as working as intended, just needed clarification.

**Comment by evansims** [comment]
No worries, I'll take a look at improving the documentation around that. Thanks again for engaging and bringing this up, I appreciate it. 👍

**Comment by Webbeh** [comment]
I guess the real issue is that there's two docs : this README and the doc on Auth0.com.

As a beginner, I followed the one on Auth0 website, which just worked. However, after switching to pho8, I wanted to update everything and tried to follow this documentation.

It's quite inconsistent between the two docs. I don't really know what's the best way to handle this kind of situation. Possibly linking the official Auth0 doc for beginners and only giving small examples in the README for specific API calls or something.

**Comment by evansims** [comment]
Could you point me to which doc on Auth0 you were using? We have stable/7.x documentation and beta/8.x documentation, you may have been referencing the earlier version's?
