### ISSUE TITLE
Login domains vs api domain

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#538]
### SDK Version

8.0.0-BETA1

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

In my auth0 account I have a "custom domain" which I send users to when they login. I use
"https://login.foo.com". 

My auth0 account has a "Management API" (or Audience) URL as "https://foo.eu.auth0.com/api/v2/". 

When I configure the SDK I use `auth.foo.com` as my domain because that will render the proper login URL. However, when I try to make a API call with Management API then I get an error back from `Management::getHttpClient()` saying: 

> Service not enabled within domain: https://login.foo.com/api/v2/

I need to use domain `foo.eu.auth0.com` to make sure Management API requests work properly.

So my question is: Have I messed up my Auth0 configuration somehow? Or do we need support to make a difference between "domain" and "login domain" in the `SdkConfiguration`?

### How can we reproduce this issue?

n/a

**Comment by Nyholm** [comment]
So here is some docs about this: https://auth0.com/docs/custom-domains/troubleshoot-custom-domains#-service-not-found-

It says that my Management API URL will still be `foo.eu.auth0.com`. 

I suggest adding a `login_domain` or `custom_domain` option to the `SdkConfiguration`.

**Comment by evansims** [comment]
Hey @Nyholm 👋 Thanks, let me look into this one and get back to you

**Comment by Nyholm** [comment]
This issue is the last blocker for me. When it is resolved I’ll be able to use v8 in prod. 

Do you want me to create a PR with a new “login domain” config value?

**Comment by evansims** [comment]
Hey @Nyholm 👋 Apologies for the delay. Working on this one today for BETA3.

**Comment by evansims** [comment]
Hey @Nyholm 👋 I've attached a PR to this issue that resolves the issue in my tests; can you confirm this solves things for you as well?
