### ISSUE TITLE
Request header or cookie too large

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#539]
### SDK Version

8.0.0-BETA1

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

This is just an FYI. Im not sure it is a problem or not. 

Time to time on my local machine nginx complains that the request header or cookie is too large. My workaround was to update the nginx config: 

```
server {
    # ...
    large_client_header_buffers 4 32k;
    # ...

    location ~ ^/index\.php(/|$) {
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}
```

I use the default storage storage set up by [SdkConfiguration](https://github.com/auth0/auth0-PHP/blob/225960b165127fb56787905ea8634bdf826f84b9/src/Configuration/SdkConfiguration.php#L389-L398)

### How can we reproduce this issue?

Not sure. I was loggin in over and over. I guess the storage was exceeding nginx default limits.

**Comment by evansims** [comment]
Hey @Nyholm 👋 Thanks for the heads-up, sounds the new encrypted cookies might just be a little big for Nginx's default settings. I'll do some testing here to make sure there isn't any issues on our end with cookie size, but either way it might be good for us to include a note in the README about it

**Comment by Nyholm** [comment]
Without looking at the code, here is some information I've learnt: 

If we want to store the values "foo", "bar", and "baz" in a cookie and we want to encrypt the data. The end result is much smaller if we combine them before encryption. 

```php
// Small
$data = ['foo', 'bar', 'baz'];
$output = encrypt(json_encode($data));


// Way way bigger
$data = [encrypt('foo'), encrypt('bar'), encrypt('baz')];
$output = json_encode($data);

```

So if we are not doing this already, we should consider adding all our data into one big map, then encrypt it and then store it in a cookie.

**Comment by evansims** [comment]
That's an excellent point, that would be a better approach to how we're doing things now (we're encrypting each individually.) Let me see what I can do toward that end

**Comment by evansims** [comment]
I've drafted a new PR that includes an updated approach to this. If you wouldn't mind, give it a look when you have some time and let me know if you think this is a better way to go. Thanks!

**Comment by evansims** [comment]
Gonna go ahead and close this since a PR is in flight to resolve it 👍 Thanks for the suggestion (as always!) @Nyholm

**Comment by Nebual** [comment]
I also ran into this, and I believe #578 is a duplicate.

In my case, we have nginx immediately in front of php-fpm which needed:
```
fastcgi_buffers  16 16k;
fastcgi_buffer_size  32k;
```
as well as an ingress nginx proxying the app container (as a dev-mode analog of our production Load Balancer) which needed:
```
proxy_buffer_size 16k;
proxy_busy_buffers_size 16k;
```

Before finding that config workaround, I believe I've identified _why_ the header is so large: in `Auth0->exchange()`, I see:
```
$this->deferStateSaving(); // good
$this->clear(); // this calls deferStateSaving(false), immediately reverting the previous line
// ... (do the exchange) ...
$this->setAccessToken(...); // this calls setcookie() since we're not deferred
$this->setAccessTokenScope(...); // calls setcookie()
$this->setRefreshToken(...); // calls setcookie()
$this->setIdToken(...); // calls setcookie()
$this->setAccessTokenExpiration(...); // calls setcookie()
$this->setUser(...); // calls setcookie()
$this->deferStateSaving(false); // this _should_ be when we call setcookie(), but we've actually had deferred=false since the early clear()
```

I'll try to make a PR proposing a fix for this shortly.

**Comment by evansims** [comment]
Hey @Nebual 👋 Great catch there, not sure how that slipped by! Looking forward to your PR! Much appreciated

**Comment by Nebual** [comment]
PR created for optimization's sake, though the resulting `Set-Cookie:` response headers are still too large for default nginx configs :(

It seems storing both the id_token and access_token, encrypted, results in quite a large default payload. I'm not sure how to better resolve this, aside from maybe mentioning it in an FAQ... ahh well!
