### ISSUE TITLE
Outdated auth0/auth0-php  Dependency 

### ISSUE THREAD

**Issue by silverxmary** [auth0/auth0-PHP#54]
Tutorial step 1. Add Needed dependencies

To install dependencies, run the following
composer require auth0/auth0-php:"~1.0"

but a recent release is available
https://github.com/auth0/auth0-PHP/releases

**Comment by mpaktiti** [comment]
Update to 3.3 with PR: https://github.com/auth0/auth0-PHP/pull/89
