### ISSUE TITLE
Make Code style part of CI

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#546]
### What should be added?

We are currently using CodeSniffer but that does not run in the CI. So our current codebase includes a bunch of errors. 

I suggest to add the following action to clearly state all CS issues: https://github.com/chekalsky/phpcs-action

**Comment by evansims** [comment]
Hey @Nyholm 👋 CodeSniffer actually runs as part of the [PHP Insights](https://github.com/nunomaduro/phpinsights) suite of tests

**Comment by Nyholm** [comment]
Hm. But when I run codesniffer locally I find a lot of errors.

**Comment by evansims** [comment]
I don't believe the `.phpcs.xml.dist` file is actually used by Insights at this point, it has its own rule set it uses, and we tweak a bit from within the `phpinsights.php` file. Sorry for the confusion! I'll check on whether we still actually use or need that file next week and get rid of it if not.

**Comment by Nyholm** [comment]
Great. I agree. Either use or remove `.phpcs.xml.dist`
