### ISSUE TITLE
How to get user after added access token

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#556]
### SDK Version

8.0.0-BETA3

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

I do a silent login. The access token is passed to me in the URL. I then add it to the Auth0 object. After that I expected (maybe wrong) to be able to call `Auth0::getUser()` and get the user back. 

However, this fails since `Auth0::getUser()` calls `Auth0::exchange()` which looks for the `code`. 

### How can we reproduce this issue?

```php
$auth0->setAccessToken((string) $request->query->get('access_token'));
$auth0->setAccessTokenExpiration($request->query->getInt('expires_in'));

// $user will always be null
$user = $auth0->getUser(); 
```

Workaround
```php
$auth0->setAccessToken((string) $request->query->get('access_token'));
$auth0->setAccessTokenExpiration($request->query->getInt('expires_in'));
$response = $auth0->authentication()->userInfo($auth0->getAccessToken());

if (!HttpResponse::wasSuccessful($response)) {
    throw new AuthenticationException('Could not get user from Auth0. Bad response,');
}

$user = HttpResponse::decodeContent($response);
```

### Additional context

I may be doing thing wrong here. Is there a better/different way to do things?

This issue touches the same code as in #524 but I believe it is separate.

**Comment by evansims** [comment]
Hey @Nyholm 👋 Nope, you're correct; that'd be the right way to go for that scenario. You can then update the local session data for the user with `Auth0\SDK\Auth0`'s `setUser()` method.

**Comment by Nyholm** [comment]
Oh. Okej. Good to know.

Thank  you
