### ISSUE TITLE
Working example with protection of specific routes by scopes would be very nice

### ISSUE THREAD

**Issue by sufius** [auth0/auth0-PHP#569]
### What should be added?

Could you please provide a boilerplate or sample project for symfony with usage of protecting routes by scopes?

**Comment by evansims** [comment]
Hi @sufius 👋 Unfortunately we don't currently have any plans for an updated Symfony quickstart I can share at this time. I've noted your interest though, and we'll take that into consideration in future planning!

In the meantime;
- You might take a look at [auth0-samples/auth0-php-api-samples](https://github.com/auth0-samples/auth0-php-api-samples) which, while not using Symfony, may give you some implementation ideas.
- There's a great third party Symfony library available that's well maintained and built upon our new 8.0 SDK available that might help with what you're looking for: https://github.com/Happyr/auth0-bundle
