### ISSUE TITLE
Unit testing auth0 implementation is highly problematic

### ISSUE THREAD

**Issue by komando82** [auth0/auth0-PHP#575]
### SDK Version

8.0

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

With new SDK 8 Version almost all auth0 package classes are final and they don't implement any interface. For example classes: `Auth0\SDK\Auth0.php`, `Auth0\SDK\Token.php`, `Auth0\SDK\API\Authentication.php`, `Auth0\SDK\API\Management` ... . 

By my opinion this is forcing the real implementation in the tests, and testing of auth0 implementation almost impossible. I don't think it is good practice to instantiate real objects in the tests with some test configuration. Because of this `@codeCoverageIgnore` have to be placed on places where Auth0 implementation is used

This is not working in the test:
PHPUnit 
```
$auth0Mock = $this->createMock(\Auth0\SDK\Auth0::class);
```
Mockery
```
$auth0Mock = Mockery::mock(\Auth0\SDK\Auth0::class);
```

For example this simple code is really hard to test
```
public function __construct(Auth0 $auth0)
{
    $this->auth0 = $auth0;
}

public function createUser(User $user, string $connection): array
{
    try {
        $response = $this->auth0->management()->users()->create(
            $connection,
            [
               'name' => $user->getName()
            ]
        );
    } catch (Auth0Exception $e) {
        throw \Exception('Cannot create user');
    }

    if (201 !== $response->getStatusCode()) {
        throw \Exception('Unsuccessful response');
    }

    try {
        $decodedResponse = $this->jsonDecode($response);
    } catch (\JsonException $e) {
        throw \Exception('Invalid Json in response');
    }

    return $decodedResponse;
}
```

I think main Auth0 classes should be mockable.

### How can we reproduce this issue?

PHPUnit 
```
$auth0Mock = $this->createMock(\Auth0\SDK\Auth0::class);
```
Mockery
```
$auth0Mock = Mockery::mock(\Auth0\SDK\Auth0::class);
```

**Comment by evansims** [comment]
Hi @komando82 👋  Thanks for your feedback. This is not something we're considering doing at this moment, but I do agree there is room for improvement here to help downstream projects ease testing that I'd like to pursue in the near future. I'll keep your suggestion in mind for further development planning for next quarter.

Meanwhile, there are workarounds you might consider, like [the `mock-final-classes` library.](https://github.com/nunomaduro/mock-final-classes) to help ease your approach.
