### ISSUE TITLE
Fail to purge auth session keys 

### ISSUE THREAD

**Issue by jngom** [auth0/auth0-PHP#576]
### SDK Version

8.0

### PHP Version

PHP 7.4

### Composer Version

2.x

### What happened?

I failed to purge auth0 session keys.
When debugging I found that the first executed session key has an empty value associated.
Because of this `current($session)` is false and the while loop ends without deleting auth0 session keys.

I suggest the following fix:
```php
public function purge(): void
    {
        $session = $_SESSION;
        $prefix = $this->sessionPrefix . '_';
        while (key($session)) {
            $sessionKey = key($session);

            if (is_string($sessionKey) && mb_substr($sessionKey, 0, strlen($prefix)) === $prefix) {
                unset($_SESSION[$sessionKey]);
            }

            next($session);
        }
    }
```

### How can we reproduce this issue?

Add a session key with an empty value
`$_SESSION["al_data"] = array();`

Init Auth0
```php
$mainConfig = array(
            'domain' 		        => getenv('AUTH0_DOMAIN'),
            'customDomain' 		=> getenv('AUTH0_CUSTOM_DOMAIN'),
            'clientId' 	                => getenv('AUTH0_CLIENT_ID'),
            'clientSecret'              => getenv('AUTH0_CLIENT_SECRET'),
            'redirectUri'               => getenv('AUTH0_REDIRECT_URI'),
            'tokenAlgorithm'            => 'RS256',
            'cookieDomain'              => getenv('AUTH0_COOKIE_DOMAIN'),
            'cookieSecret'              => getenv('AUTH0_COOKIE_SECRET'),
        );

$sdkConfig = new SdkConfiguration($mainConfig);
$sdkConfig->setSessionStorage(new SessionStore($sdkConfig, $sdkConfig->getSessionStorageId()));
$this->auth0 = new Auth0($sdkConfig);
```

In **SessionStore**, `$this->sessionPrefix` is equals to **auth0_session**

The while loop always starts with the al_data session key and ends.

**Comment by evansims** [comment]
Hey @jngom 👋 Thanks for raising this; let me look into it further and get back with you.

**Comment by jngom** [comment]
My pleasure! 👍🏾
