### ISSUE TITLE
Domain should be necessary on Management instanciation

### ISSUE THREAD

**Issue by MariusJam** [auth0/auth0-PHP#583]
### SDK Version

8.0

### PHP Version

PHP 7.4

### Composer Version

2.x

### What happened?

Given the following code :

```php
$token = $this->auth0TokenRetriever->getToken();
        $managementApi = new Management(
            new SdkConfiguration(
                ["managementToken" => $token, "strategy" => "management"]
            )
        );

        return $managementApi->clients()->update($this->auth0SalaryClientId, [
            'web_origins' => $salaryAllowedWebOrigins,
        ]);
```

We get the following Exception: `Unable to parse URI: https:///api/v2/clients/XXXXXXXX` => there is no domain in the url.

A check should be implemented to ensure the domain is set when instantiating Management or SdkConfiguration. 

### How can we reproduce this issue?

See code above.

**Comment by evansims** [comment]
Hey @MariusJam 👋 Thanks for the heads-up! You're quite right that check should be getting made on the `management` strategy as well, just an oversight. I'll get a PR up to fix that next week.
