### ISSUE TITLE
Missing updateAppMetadata() method?

### ISSUE THREAD

**Issue by vboctor** [auth0/auth0-PHP#59]
I noticed the following methods in Auth0.php, but no method to update AppMetadata for the user.

    updateUserMetadata($metadata)
    getUserMetadata()
    getAppMetadata()

Any reason for this?  Is there a way to set app metadata in the version on composer?

**Comment by glena** [comment]
the thing is you need an api token for app metadata. It uses the user token for user metadata. Check the api (users->update)
