### ISSUE TITLE
Lcobucci\JWT namespace conflict

### ISSUE THREAD

**Issue by nanofelis** [auth0/auth0-PHP#596]
### SDK Version

7.9

### PHP Version

PHP 8.1 (In Development)

### Composer Version

2.x

### What happened?

The [php-jwt](https://github.com/auth0/php-jwt) lib used by auth0 is a fork from the original [Lboccuci](https://github.com/lcobucci/jwt https://github.com/auth0/php-jwt) jwt lib.

However the namespace used in auth0/php-jwt has not been changed and is still targeting the original namespace Lcobucci\JWT, for instance: 

[src/Builder.php](https://github.com/auth0/php-jwt/tree/master/src/Builder.php)
```
<?php
declare(strict_types=1);

namespace Lcobucci\JWT;
```

The issue is that we also have the original Lcobucci library installed through others dependencies and the two are conflicting over this identical namespace.
 

### How can we reproduce this issue?

Install both librarie, auth0/php-jwt and lcobucci/jwt.

**Comment by evansims** [comment]
Hi @nanofelis 👋 This has been addressed in [previous issues](https://github.com/auth0/auth0-PHP/issues?q=Lcobucci). You will need to upgrade to V8 of this library to resolve issues with that dependency.
