### ISSUE TITLE
Pass accessToken to embedded frontend react app 

### ISSUE THREAD

**Issue by jithureddy** [auth0/auth0-PHP#601]
### SDK Version

`"auth0/auth0-php": "^5.1"`

### PHP Version

PHP 7.4

### Composer Version

2.x

### What happened?

I have react app embedded in Drupal page
I am using auth0 (https://www.drupal.org/project/auth0) module for SSO.

I want to use access token in my embedded react app by fetching access token from Drupal user session

I can access $accessToken = $this->auth0->getAccessToken(); like this but not sure how to expose to react app

 ```
// Set store to null so that the store is set to SessionStore.
    $this->auth0 = new Auth0([
      'domain'        => $this->helper->getAuthDomain(),
      'client_id'     => $this->clientId,
      'client_secret' => $this->clientSecret,
      'redirect_uri'  => "$base_root/auth0/callback",
      'persist_user' => FALSE,
    ]);

    $userInfo = NULL;
    $refreshToken = NULL;

    // Exchange the code for the tokens (happens behind the scenes in the SDK).
    try {
      $userInfo = $this->auth0->getUser();
      $idToken = $this->auth0->getIdToken();
      $accessToken = $this->auth0->getAccessToken();
      // $auth0TokensStore = \Drupal::service('user.private_tempstore')->get('auth0Tokens');
      $this->tempStore->set('accessToken', $accessToken);
      $this->auth0Logger->notice('$accessToken');
      $this->auth0Logger->notice($accessToken);
    }
```

### How can we reproduce this issue?

Any single page application embedded in Druapl

**Comment by evansims** [comment]
Hi @jithureddy 👋 

- You didn't specify which version of the SDK you're using, could you clarify?
- The Drupal module you mentioned is no longer supported and I have not worked with it personally, so my advice will be limited there.
- Are you implementing this integration using the PHP SDK or the Drupal module? I can only advise on SDK usage.
- Can you explain your integration flow for me? I think you're suggesting you are authenticating through a PHP app and want to expose that session to a React frontend?

**Comment by evansims** [comment]
Assuming my understanding of your integration is correct, you cannot directly pass an access token to a frontend SPA SDK.

If possible, ideally, I would suggest performing this flow the other way around: authenticate with the SPA (in this case `auth0-react`) and then pass the access token to your PHP backend to authorize requests.

Otherwise, you will need to perform a silent authentication using the React SDK's `getTokenSilently()` method. I don't recommend this approach because you'll end up with two types of local sessions (one on the PHP side and the other on React) which could drift in state, and will require more work on your end to properly handle both during a user logout.

**Comment by jithureddy** [comment]
Hi @evansims. Thanks for responding 👍 . 

I have updated the SDK version.

I am doing the integration with Auth0 Drupal Module but I can extend this Drupal module which is using PHP SDK internally.

My application flow looks like below. Here External API is another custom api (Not drupal backend) which is secured with Auth0

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/5911189/154842003-84d58c75-cb86-4ccf-b4ae-130470d85039.png">

If I use `auth0-react` SDK's  `getTokenSilently()`, with in the embedded react app, there will be another user session. 
I want to use the Drupal Auth0 session instead, as I need to implement Drupal webhook which will be eventually has to be secured with Auth0.

Any help or suggestion would be 💯  appreciated

**Comment by evansims** [comment]
Hi @jithureddy

Thanks for clarifying! Be advised, the Drupal module incorporating PHP SDK 5.0 is a concern, as it too is deprecated and unsupported. Although I have not tested it, I would strongly suspect that, when [PHP drops 7.x branch support this November](https://www.php.net/supported-versions.php), it will not behave correctly under PHP 8.0+. I'd recommend migrating to PHP SDK 8.

I sympathize with your development intention here, but it's simply not possible to directly apply the Drupal session you're establishing to the React SDK frontend in this manner. The single-page application SDKs like React do not have a means of initializing with an existing ID or Access Token, as you're describing.

Given your app setup here, I don't think you really have any option other here but to incorporate silent authentication in your React frontend. This will reuse the existing Auth0 session established by your PHP backend — but, as you mentioned, this means two sessions floating around you'll need to think about.

I wouldn't advise it, but looking beyond "packaged" solutions we provide, you could build something custom for your React frontend to consume a token inserted in generated HTML by your PHP app. Then you could forward that token for your custom API calls. Obviously, that is something outside the scope of our SDKs that I can't really advise on, but it would be possible.

**Comment by jithureddy** [comment]
@evansims Thanks for the input
