### ISSUE TITLE
Management::getHttpClient errors are opaque when acquiring token

### ISSUE THREAD

**Issue by sepiariver** [auth0/auth0-PHP#603]
### What should be added?

Thanks for all the great work on the latest version. Huge upgrade! The migration from 7.x is a bit painful but sometimes you gotta just bite the bullet to get the benefits :)

Especially love the more tightly integrated Management and Authentication subclasses, and the new methods to instantiate them.

Something that could have been helpful—might be helpful for others as well—is that when calling `->management()` it tries to acquire a `managementToken` (amazing, thanks for that) but in https://github.com/auth0/auth0-PHP/blob/main/src/API/Management.php#L165 a `ConfigurationException::requiresManagementToken()` is called for any condition that could lead to a failure to acquire the token.

After spending many hours debugging, it became evident that an error response was being returned from the API:

> "Client is not authorized to access "<tenant>/api/v2/". You need to create a "client-grant" associated to this API. See: https://auth0.com/docs/api/v2#!/Client_Grants/post_client_grants"

This message is very helpful indeed, and was clearly written for a human to take some action, however it was _entirely swallowed_ and obfuscated with the `ConfigurationException`.

Proposal: an API error response exception class (if it doesn't already exist?) and throwing that when the API has something to say about the issue. If I can manage it in a decent timeframe, I'll submit a PR :)

**Comment by Webbeh** [comment]
Thanks for that issue. I got the same problem the first time I needed to get a management token, and I really don't even remember how I figured out where that message came. I think it was in the Auth0 logs but I'm not even sure.

Making it more evident would be great indeed, would have saved me a headache !

**Comment by evansims** [comment]
Hey @sepiariver 👋 Thanks for your feedback! You raise a good point, and I'm sorry that led to confusion in figuring out what was wrong there. As @Webbeh mentioned, there should have been something in your Auth0 logs to identify this AFAIK, but I agree this is a potential pain area we could and should improve by exposing an exception type in this case.

If you'd like to submit a PR that would be most welcome, but otherwise I'll try to get to this ASAP

**Comment by sepiariver** [comment]
Cool thanks for the heads up :)

mom just going through existing exception classes (names) to ensure consistency and also trying to determine if API error responses always have the same payload structure 

once I figure that out I should be able to submit a PR
