### ISSUE TITLE
Docu wrong regarding decoding access token?

### ISSUE THREAD

**Issue by AndreasA** [auth0/auth0-PHP#611]
### SDK Version

8.0

### PHP Version

PHP 8.1 (In Development)

### Composer Version

2.x

### What happened?

In the docu here: https://github.com/auth0/auth0-PHP#decoding-an-access-token

Code is `$token = $auth0->decode('{{YOUR_ACCESS_TOKEN}}', null, null, null, null, null, null, \Auth0\SDK\Token::TYPE_ID_TOKEN);`

but I guess it should be
`$token = $auth0->decode('{{YOUR_ACCESS_TOKEN}}', null, null, null, null, null, null, \Auth0\SDK\Token::TYPE_TOKEN);`

or with PHP 8.x it could be:

`$token = $auth0->decode(token: '{{YOUR_ACCESS_TOKEN}}', tokenType: \Auth0\SDK\Token::TYPE_ID_TOKEN);`

the type passed to decode is TYPE_ID_TOKEN but shouldn't it be TYPE_TOKEN for access tokens?

**Comment by evansims** [comment]
Hey @AndreasA 👋 You're correct, was a typo on our part! I've updated the README. Thanks for the heads up!

**Comment by AndreasA** [comment]
@evansims Thanks for fixing it so fast.
