### ISSUE TITLE
Majority of Guardian API support in the SDK missing

### ISSUE THREAD

**Issue by larrydahooster** [auth0/auth0-PHP#615]
### What should be added?

I wanted to use the [/Guardian/post_ticket](https://auth0.com/docs/api/management/v2#!/Guardian/post_ticket) as suggested in [Create Custom Enrollment Tickets](https://auth0.com/docs/secure/multi-factor-authentication/auth0-guardian/create-custom-enrollment-tickets) but the PHP SDK is only offering 3/24 endpoints:

- /Guardian/get_factors
- /Guardian/get_enrollments_by_id
- /Guardian/delete_enrollments_by_id

**Comment by evansims** [comment]
Hi @larrydahooster 👋 Thanks for your suggestion. This is on our radar to expand support on within the SDK, but we do not currently have a timeline we can provide.

**Comment by larrydahooster** [comment]
Okay, I just figured out that I can use the public httpclient to build my own requests. Nevermind.
