### ISSUE TITLE
520 error in Cloudflare

### ISSUE THREAD

**Issue by khamazaspyan** [auth0/auth0-PHP#618]
### SDK Version

8.0

### PHP Version

PHP 8.1 (In Development)

### Composer Version

2.x

### What happened?

After upgrade packages versions(auth0/auth0-php 7.9.1 to 8.1 and auth0/login 6.5 to 7.0) auth0 is storing too large cookie.
We are using Cloudflare witch have limit for 16kb, and after login I'm getting 520 error witch related with large cookie size.

PHP version is 8.1.4
Laravel version is 9.6.0.

How can I reduce cookie size?

### How can we reproduce this issue?

Just need to run application on cloudflare

**Comment by evansims** [comment]
Hi @khamazaspyan 👋 It's not possible to adjust the cookie size produced by the SDK, it only contains what is necessary for the SDK to perform its functions. If Cloudflare does not allow you to increase cookie size limits, you may need to use an alternative session storage interface. In your case, the SessionStore is most likely your best route — it just uses the native PHP sessions to store the data. You can assign this during SDK initialization using the 'sessionStorage' property and using an `Auth0\SDK\Store\SessionStore` instance your application creates beforehand.

There are important considerations to make when using PHP sessions, however; for example, if you are using a load balancer and have your PHP app scaled across multiple "machines" (whatever that may look like), you need to ensure your PHP sessions are stored in a manner that is shared and accessible across all those instances, or the SDK will not be able to retrieve the session details successfully. This isn't an SDK issue so much as a PHP configuration issue, but it is often overlooked. You can use something like the [memcached](http://www.php.net/manual/en/memcached.sessions.php) extension to store those in a shared memcache server somewhere, for example.

**Comment by evansims** [comment]
@khamazaspyan Are you referring to usage with [our Laravel SDK](https://github.com/auth0/laravel-auth0), or building something custom?

**Comment by khamazaspyan** [comment]
@evansims I'm using your Laravel SDK

**Comment by evansims** [comment]
Understood; for future reference, questions on the Laravel SDK [should be opened on its repository](https://github.com/auth0/laravel-auth0). 👍 The Laravel SDK [does not currently](https://github.com/auth0/laravel-auth0/issues/273) support the SessionStorage medium, but support for that is coming in 7.1.

**Comment by evansims** [comment]
I don't currently have a timeline I can share, but it's on our radar for an update in the near term.

**Comment by roberttolton** [comment]
@evansims Any update on this?
