### ISSUE TITLE
PR to fix deprecation notice to use Token::claims()->get()

### ISSUE THREAD

**Issue by Bird87ZA** [auth0/auth0-PHP#621]
### SDK Version

7.5

### PHP Version

Other (specify in 'additional context')

### Composer Version

2.x

### What happened?

When we decode a token that has an array of audiences it gives us the following deprecation notice:

```You will only get the first array entry as a string. Use Token::claims()->get() instead.```

This is triggered by `\Lcobucci\JWT\Token:236`.

### How can we reproduce this issue?

Checkout tag 7.5.0 and validate a token with `aud` as an array

### Additional context

Due to the age of our app, and the inability to update to later packages, it's impossible for us to get rid of this slight hindrance. In prod, error's aren't reported so it's not a problem, but on local, it breaks anything that required authentication, due to the json return not being valid.

I want to know if it would be frowned upon if I create a PR to fix this in a minor release for 7.5.x. Would this be possible and can it be released as 7.5.1 if I make a pr to the 7.5 tag or would this cause more headaches for you than it's worth?

Thanks for taking the time to read.

**Comment by evansims** [comment]
Hey @Bird87ZA 👋 Thanks for the heads-up! If you'd be willing to contribute a PR to fix that, it would be most welcome! 👍
