### ISSUE TITLE
callback function upon successful login

### ISSUE THREAD

**Issue by handhikadj** [auth0/auth0-PHP#631]
### What should be added?

I want to execute some function only right after successful login

for example
```php
$callback = function () {
    // ...
}
(new Auth0($options))->login($callback);
```

**Comment by evansims** [comment]
Hi @handhikadj, unless I'm misunderstanding your request, this functionality could be built into your application's callback route. After the authentication flow is complete and the end user is redirected to your app's callback route (where the 'exchange' method is called) simply handle your logic there.
