### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Webbeh** [auth0/auth0-PHP#637]
### SDK Version

8.2

### PHP Version

Other (specify in 'additional context')

### What happened?

The `$auth0->exchange()` method was updated in v8 to not return `false` anymore, but throw Exceptions.

It would be good to update the [Requesting Tokens](https://github.com/auth0/auth0-PHP/#requesting-tokens) part of the README to be in accordance with those changes.

An example of those changes can be found in https://github.com/auth0/auth0-PHP/issues/524#issuecomment-916501837

If we use the README's example, the only thing we get is an uncaught StateException.

### How can we reproduce this issue?

Follow the readme as it is right now and try to use a previously logged in session.

**Comment by evansims** [comment]
Thanks @Webbeh 👋 An oversight on my part in porting the documentation. I've updated the README to reflect expected usage now.

**Comment by Webbeh** [comment]
Anytime.
Thank you

**Comment by Webbeh** [comment]
What's the cleanest way to handle that exception?

I have customers who bookmarked the URL of the WebApp with the state and code URL parameter. If they end their session and they call that URL, the StateException is thrown every time.

Should I just replace the error message with a call to `$auth0->clear();` followed by `$auth0->login();` ?

**Comment by evansims** [comment]
Hey @Webbeh 👋 That would work, just keep in mind that if you catch and redirect to login within your callback route, you could potentially create an infinite redirect loop if there are some weird circumstances, like the end user blocking cookies. Showing an interstitial page with an error message and offering to redirect the user back to your login route to try again would introduce an extra step, but might be a safer route.

**Comment by Webbeh** [comment]
Maybe I should redirect them to the `logout` page instead then. 

That error would appear way too often - everyone who bookmarked a page including the `code` and `state` url parameters would be affected everytime they re-open a browser window using that bookmark, which is actually what made me notice the outdated README.

Getting rid of those parameters when bookmarking would probably be a better solution...
