### ISSUE TITLE
Auth0 8.3.0 now requires "cookieSecret" configuration

### ISSUE THREAD

**Issue by shadowhand** [auth0/auth0-PHP#648]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### What happened?

Upon upgrading from 8.2.1 to 8.3.0, the following error appears without any other changes:

```
Auth0\SDK\Exception\ConfigurationException: `cookieSecret` must be configured
```

I have no problem making this change, but the README says that `cookieSecret` is `string|null`, which implies that it is an optional parameter.

### How can we reproduce this issue?

```php
$config = new SdkConfiguration(
    domain: getenv('AUTH0_DOMAIN'),
    clientId: getenv('AUTH0_CLIENT_ID'),
    clientSecret: getenv('AUTH0_CLIENT_SECRET'),
);
```

**Comment by evansims** [comment]
Hey @shadowhand 👋 Sorry for the trouble there, and thanks for letting me know. I'm not entirely certain why a jump from 8.2.1 to 8.3.0 would have manifested that error for you, but there were some changes to SdkConfiguration in 8.3 that may have brought it to light. I'll investigate further. In any event, that is correct behavior, with the default `strategy` of `webapp`, a `cookieSecret` is required.

(Although, if you aren't using sessions in your app (i.e. you're just authorizing access tokens from a frontend), you can set `strategy` to `api` to avoid configuring cookies: https://github.com/auth0/auth0-PHP#configuration-strategies)

**Comment by shadowhand** [comment]
@evansims `strategy` seems to be the option we needed to set, rather than `cookieSecret`! Thanks!
