### ISSUE TITLE
getUser() now returns null

### ISSUE THREAD

**Issue by tjmahaffey** [auth0/auth0-PHP#661]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### What happened?

Ever since I ran a composer update a few days ago, what used to fetch the current user now returns null.

### How can we reproduce this issue?

$configuration = new SdkConfiguration(
             // 🧩 Include other required configuration options, such as those outlined in the 'SDK Initialization' step above here.
             domain:  env('AUTH0_DOMAIN'),
             clientId:  env('AUTH0_CLIENT_ID'),
             clientSecret:  env('AUTH0_CLIENT_SECRET'),
             cookieSecret:  env('AUTH0_COOKIE_SECRET'),
             managementToken: "token here"
         );

$auth0 = new Auth0($configuration);
$user = $auth0->getUser();

### Additional context

auth0-php version 8.3.4
PHP 8.1.10
Laravel 9.36.4

**Comment by evansims** [comment]
Hi @tjmahaffey! 👋 Sorry to hear you're hitting some issues here.

I'm not able to replicate your issue yet, but I'm still looking into it. Have you tried reauthenticating since updating to 8.3.4? There was a bug that's fixed in 8.3.4 in which if a `scope` was not configured the SDK would not used the default scope of 'openid profile email' as it should have — this meant that authentication technically succeeded, but no profile was returned from the API, which means nothing to return from `getUser()`. If you happened to authenticate on an SDK version that was affected your session would still be missing that data, but re-authenticating should fix that.

Let me know if you've given that a go and we can try some other things, but that stands out as the most obvious cause offhand. Thanks for your patience and help on this!

**Comment by tjmahaffey** [comment]
I'm having a hard time figuring this out.
I can get the token.
I can instantiate Auth0 with the configuration.
But $auth0->getUser() is always null.

Yes, I have tried re-authenticating several times. Same result every time.

**Comment by evansims** [comment]
Hi, @tjmahaffey 👋 Sorry to hear you're still hitting a problem there.

Would you mind sharing the code you're using to do your authentication flow? In particular, how you're doing login and handling the callback would be helpful in troubleshooting. We might be overlooking something I can address before I begin digging deeper into the SDK.

In terms of `usersByEmail()` calls from the Management API, I'd need to know more about your use case to advise you there. What are you needing to achieve with your app on this?

**Comment by tjmahaffey** [comment]
So, I'm using the auth0/login package for Laravel for authentication.
But I'm using the auth0-php package for Management API calls.

My flow performs standard authentication via the auth0/login package.
Then, when the user is OK'ed and routed to our internal app dashboard, I'm trying to read the user's metadata from Auth0 to set up some permissions on our side. That's where I first noticed this getUser() issue crop up for me.

This is what my code looked like for fetching metadata from Auth0 after authentication succeeded.
NOTE: I have a helper method set up in the same class that generates the token. That's what this is: $this->getAuth0Token().

`    public function getUserMetaData() {

        $configuration = new SdkConfiguration(
             // 🧩 Include other required configuration options, such as those outlined in the 'SDK Initialization' step above here.
             domain:  env('AUTH0_DOMAIN'),
             clientId:  env('AUTH0_CLIENT_ID'),
             clientSecret:  env('AUTH0_CLIENT_SECRET'),
             cookieSecret:  env('AUTH0_COOKIE_SECRET'),
             // The process for retrieving an Access Token for Management API endpoints is described here:
             // https://auth0.com/docs/libraries/auth0-php/using-the-management-api-with-auth0-php
             managementToken: $this->getAuth0Token()
         );

        $auth0 = new Auth0($configuration);
        // Request users from the /users Management API endpoint
        $management = $auth0->management();

         try {
            $user = $auth0->getUser();
         } catch (\Exception $e) {
            $user = null;
         }

         if ($user) {

             $userId = $user['sub'];

              // Fetch the user from the /users endpoint by the authenticated user's ID.
              $userResponse = HttpResponse::decodeContent($management->users()->get($userId));

              if ($userResponse) {

                  return (object) $userResponse['user_metadata'] ?? [];

             } else {
                 return null;
             }

         } else {
             return null;
         }

    }`

**Comment by tjmahaffey** [comment]
@evansims - Man. I really appreciate this.

Thank you SO much. Please consider my thread closed.

**Comment by evansims** [comment]
@tjmahaffey No worries, I'm sorry for the confusion! But I'm glad we could get your issue sorted. Please do let me know if you have any further problems down the line. Good luck with the app!
