### ISSUE TITLE
Recent changes break existing auth0/login configuration

### ISSUE THREAD

**Issue by bluehaoran** [auth0/auth0-PHP#664]
### SDK Version

8.3

### PHP Version

PHP 8.1

### What happened?

Recent changes to this library (#659) and to the Laravel library (auth0/login, https://github.com/auth0/laravel-auth0/commit/e132b28b9fb623339ba1f236f6430effa29f2c89) break backward compatibility.

`SdkConfiguration::setScope()` no longer handles a `null` empty value correctly. Although the recent change to auth0/login corrects this for anyone who installs and publishes the Laravel configuration after auth0/login:7.2.2, anyone with an **existing configuration** file (which would have code like this: `Configuration::stringToArrayOrNull(env('AUTH0_SCOPE')),`)  will default their scope to null.

This library should be able to handle both empty states, empty array and null.

I suggest patching to replace `if ([] === $scope)` with `if (empty($scope)) {` in SdkConfiguration::setScope.

There may be additional test cases required here.

### How can we reproduce this issue?

- Install Laravel.
- Composer-require auth0/auth0-php:8.3.0.
- Composer-require auth0/login:7.1.0.
- `php artisan vendor:publish --tag=auth0-config`
- set up the rest of the app per the instructions.
- Loosen Composer requirements to `auth0/auth0-php:^8.3.0` and `auth0/login:^7.1.0`
- composer update
- confirm that `Validation of "scope" was unsuccessful` is reported.

**Comment by evansims** [comment]
Hi @bluehaoran 👋 Totally in agreement, that was an oversight on my part. Thanks for catching that. I'll get a fix going.
