### ISSUE TITLE
Provided state breaks the flow with "Invalid state" error

### ISSUE THREAD

**Issue by winstoncl** [auth0/auth0-PHP#673]
### SDK Version

8.2

### PHP Version

PHP 8.1

### What happened?

Providing a state to the SDK's **login** function does not store it in TransientStorage - fails when verifying, and returns 'Invalid state' error.

This is because is line 105 of Auth0.php a new nonce is issued to the provided state, instead of storing it in transient store.

I expected the provided state to be used just fine.

### How can we reproduce this issue?

Create a state and pass it into the login function, something like:
$config = new SdkConfiguration(...);
$sdk = new Auth0($config);
$state = bin2hex(random_bytes(16));

// pass state in '$params' parameter
$sdk->login(null, ['state' => $state]);

**Comment by evansims** [comment]
Hey @winstoncl 👋 Thanks for creating this issue

On the return trip, are you also providing that state to [the `exchange` method](https://github.com/auth0/auth0-PHP/blob/a982fc9607cacedcc5298883af45f70a7f3f6423/src/Auth0.php#L250)? The expectation for passing a `state` parameter of your own is for the host application to handle the storage and retrievable of this value internally as needed. Although we could store this in the transient storage medium on the SDK side, that would be a breaking change from previous behavior.

**Comment by winstoncl** [comment]
Hi @evansims , thank you for your quick response!  :)
No, we do not provide the state to the `exchange` method. However if we don’t provide the state to the exchange method, it [gets it from the request parameters by default](https://github.com/auth0/auth0-PHP/blob/a982fc9607cacedcc5298883af45f70a7f3f6423/src/Auth0.php#L262), so I don’t think providing the state ourselves would change anything. 

We initialise the Auth0 instance with a SdkConfiguration instance, which [by default sets the transient storage to be CookieStore](https://github.com/auth0/auth0-PHP/blob/a982fc9607cacedcc5298883af45f70a7f3f6423/src/Configuration/SdkConfiguration.php#L1226).

However in Auth0.login() the [state is not stored in transient storage ](https://github.com/auth0/auth0-PHP/blob/main/src/Auth0.php#L105)(and as you have mentioned, storing it would be a breaking change from expected behaviour in V8) and later on in Auth0.exchange() we [try to 'verify' the state](https://github.com/auth0/auth0-PHP/blob/main/src/Auth0.php#L270) by [getting it from the transient store](https://github.com/auth0/auth0-PHP/blob/main/src/Utility/TransientStoreHandler.php#L108) (which again, by default, is the  CookieStore).

So I think ultimately the Auth0 sdk does try to get the state from a cookie but it was not stored beforehand, and thus fails?

**Comment by evansims** [comment]
Ahhh, I see what you're saying now — yup, that's a good catch, and you're 100% right. I'll get a fix sorted for that when the team gets back from vacation next week, and update you when it's ready! Thanks!
