### ISSUE TITLE
 "cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",

### ISSUE THREAD

**Issue by dungphanxuan** [auth0/auth0-PHP#69]
Hello, i use auth0 api to create new user and get error:
 "cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",

How can i fix it! thank

**Comment by glena** [comment]
check the readme :) `I am getting curl error 60: SSL certificate problem: self signed certificate in certificate chain on Windows` :point_right: https://github.com/auth0/auth0-PHP#i-am-getting-curl-error-60-ssl-certificate-problem-self-signed-certificate-in-certificate-chain-on-windows
