### ISSUE TITLE
Migrating from PHP SDK 7 to 8 - session not persisting

### ISSUE THREAD

**Issue by iandavidwild** [auth0/auth0-PHP#703]
### Checklist

- [X] The issue can be reproduced in a a sample app (either [webapp](https://github.com/auth0-samples/auth0-php-web-app) or [api](https://github.com/auth0-samples/auth0-php-api-samples)) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-PHP#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-PHP/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-PHP/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-php) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.3

### PHP Version

PHP 8.0

### Description

I’m currently (successfully) using version 7 of the Auth0 PHP SDK to implement single sign on. I’m using the Authentication class directly so that I can manage each step of the authentication flow. Once the authentication flow has completed, I then access the user details by creating a new instance of the Auth0 class (with the appropriate client details). However, when testing the same using version 8 of the SDK the cookie store is empty and the ‘state’ variable is null. We’ve tried modifying the cookie settings but without any joy. I’ve been working through the documentation checking that we’ve updating our cookie settings appropriately but, try as we might, we can’t seem to get user details to persist between executing the authentication flow using the Authentication class and instantiating an Auth0 class. Is there something we’re missing? As I say, it works fine with v7 of the SDK but there’s something we’re not doing in v8.

### How can we reproduce this issue?

1. Authenticate using the Authentication class.
2. Create a new instance of the Auth0 class using the same client credentials as step 1.
3. In Auth0 SDK version 7 the user credentials are found in the persistent store. In version 8 they aren't (state is null).

**Comment by evansims** [comment]
Hi @iandavidwild 👋 Sorry to hear you're having some troubles there, but I'm sure we can get you sorted there.

The Authentication class offers methods for all the raw Authentication API endpoints, but does not work with any stateful awareness. All the session handling is performed through the Auth0 class.

For you should use `Auth0\SDK\Auth0::login()` and on the return trip use `Auth0\SDK\Auth0::exchange()` to complete the authentication flow. If you need more low-level control on the process, you'd need to emulate the functionality of those two methods within your own code.

If this is roughly the approach you've followed, we can troubleshoot further if you can share the relevant portions of your code.

**Comment by iandavidwild** [comment]
Hi @evansims and thanks for your message. So we've been carrying out some further testing, which has included rewriting the code to use an instance of Auth0 instead of Authentication. And things are better but still not quite right. I should say that our use case is slightly unusual because:
- a user can potentially authenticate using two different clientids/client secrets in the same browser session.
- we need to add three extra key->value pairs to the transient cookie, auth0_transient. This is because our users are accessing our webapp through different routes and each root logs in using a different user account (which explains the previous bullet).

Here is the code that sets key->value pairs in the transient cookie:

```
// Get a instance of SdkConfiguration object.
$autosdkconfig->new SdkConfiguration(array(
    'domain' => $domain,
    'clientId' => $clientid_route1,
    'clientSecret' => $clientsecret_route1,
    'cookieSecret' => $cookiesecret,
));

// Generate and store a state value.
$store = $autosdkconfig->getTransientStorage();
$statehandler = new TransientStoreHandler($store);
$statevalue = $statehandler->issue('state');
// Store state parameters.
foreach ($stateparams as $key => $value) {
    $store->set($key, $value);
}

// Call authorization endpoint by setting page header - we need to pass extra parameters so have to do this programmatically.
```

This is currently how we are handling the response from the 'signin' endpoint:

```
// We need to check the auth0_transient cookie to determine which route we are using to authenticate (i.e. which clientid/secret).
// This means it doesn't matter which client id and secret we use...
$autosdkconfig->new SdkConfiguration(array(
    'domain' => $domain,
    'clientId' => $clientid_route1,
    'clientSecret' => $clientsecret_route1,
    'cookieSecret' => $cookiesecret,
));

$transientstore = $auth0sdkconfig->getTransientStorage();
$statehandler = new TransientStoreHandler($transientstore);

$additionaldata['route'] = $statehandler->getOnce('route');

// Now we know the route we can continue the authentication flow using the correct client id and secret
$autosdkconfig->new SdkConfiguration(array(
    'domain' => $domain,
    'clientId' => ($additionaldata['route'] == 'route_1')?$clientid_route1:$clientid_route1,
    'clientSecret' => ($additionaldata['route'] == 'route_2')?$clientid_route2:$clientid_route2,
    'cookieSecret' => $cookiesecret,
));

...
```

What we're noticing is that sometimes (not every time) the auth0_transient cookie isn't being removed and this is giving us a 'Bad request' browser message (i.e. "corrupted" cookies). If we delete the auth0_xxx cookies so they are re-created all is fine. My initial thoughts were:
- perhaps we should be storing the three extra key->value pairs in a different cookie (not auth0_transient)?
- can we specify custom cookie names for the two different login routes?

I do feel there is something I'm missing somewhere. I'm hoping all this makes enough sense that you'll be able to point me in the right direction.

Thanks again!

**Comment by evansims** [comment]
Hey again @iandavidwild 👋 Thanks for the additional information there!

> perhaps we should be storing the three extra key->value pairs in a different cookie (not auth0_transient)?

I wouldn't recommend binding any custom data to the transient cookie handler directly. That data store is* intended to be emptied after the `exchange()` completes. Best to use a separate carrier from the SDK for that, perhaps a PHP session. I think you bring up a good point though, I'm sure it's a common desire to be able to do that — I'll think about how we could approach that for a future update.

> can we specify custom cookie names for the two different login routes?

Absolutely! During the initialization of each of your SdkConfiguration instances, you can pass custom values for the `transientStorageId` and/or `sessionStorageId` properties.

```php
$auth0 = new Auth0(new SdkConfiguration(
    domain: '...',
    clientId: '...',
    clientSecret: '...',
    cookieSecret: '...',
    transientStorageId: 'example_client_temporary',
    sessionStorageId: 'example_client_persistent',
));
```

Or, you can use the `setTransientStorageId()` and/or `setSessionStorageId()` setter methods to change it after the fact. This will effectively change the prefixing of the data stores—in the case of the default CookieStore interfaces, the prefixes of the cookie names.

```php
$config = new SdkConfiguration(...);
$auth0 = new Auth0($config);

$config->setTransientStorageId('example_client1');
```

Or

```php
$auth0 = new Auth0(new SdkConfiguration(...));
$auth0->configuration()->setTransientStorageId('example_client1');
```

If you'd like to keep your custom key-value storage and the SDK state data in one place, you could consider using the `Auth0\SDK\Store\SessionStore` interface instead, and just keep everything in a native PHP session. For example,

```php
$config = new SdkConfiguration(
    domain: '...',
    clientId: '...',
    clientSecret: '...',
    cookieSecret: '...'
));

// Because we need to pass our configuration instance to the SessionStore, we have to create it after the configuration ...
$sessionState = new SessionStore($config);

// And then hand it back to the configuration instance ...
$config->setSessionStorage($sessionState);
$config->setTransientStorage($sessionState);

// Important: use this in place of session_start() to start the PHP session. This will set up the cookies for the session to match your SDK configuration.
$sessionState->start();

// Then you can just work with the standard PHP session variables:
$_SESSION['example'] = 'test';
```

Just another approach to consider there.

* I think I might see a bug relating to the corrupted transient cookie you mentioned, thanks for pointing that out. I'll investigate.

**Comment by iandavidwild** [comment]
Hi @evansims, thanks for this. I've just been taking another look at our code and realized that we needed to be expiring the Auth0 session cookies (not the transient cookie) before beginning the authentication flow. I think this will avoid (at least in Chrome and Edge, where I've been testing) a "Bad request" error when either of our authentication routes is taken if you're already logged in. We'll carry on testing and let you know if we encounter any issues. I would like to leave this issue open in the meantime, if that's okay?

If you do find an issue with the transient cookie then please do let me know if you needed us to carry out any testing.

Many thanks again for your help - it's much appreciated 👍
