### ISSUE TITLE
Browser Header Field Exceeds Limit

### ISSUE THREAD

**Issue by devops-at-alinea** [auth0/auth0-PHP#706]
### Checklist

- [X] The issue can be reproduced in a a sample app (either [webapp](https://github.com/auth0-samples/auth0-php-web-app) or [api](https://github.com/auth0-samples/auth0-php-api-samples)) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-PHP#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-PHP/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-PHP/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-php) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.3

### PHP Version

PHP 8.1

### Description

auth0/auth0-php: ^8.4
I am following the PHP SDK quickstart here https://auth0.com/docs/quickstart/webapp/php using a new workspace (e.g. I'm not incorporating the example into an existing project).

After the callback is handled when the flow gets redirected back to the homepage of the sample app:
```php
        // Have the SDK complete the authentication flow:
        $auth0->exchange(ROUTE_URL_CALLBACK);
    
        // Finally, redirect our end user back to the / index route, to display their user profile:
        header("Location: " . ROUTE_URL_INDEX);
        exit;
```

I get the following warning in Chrome (Incognito) - Version 110.0.5481.178 (Official Build) (64-bit)
```
Bad Request
Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
```
 The following image shows the size of the cookies in the response:

![Screenshot 2023-03-01 103848](https://user-images.githubusercontent.com/10514031/222118410-e6a43cb2-03ca-4658-93e2-7f6161230ab6.png)

### How can we reproduce this issue?

Use the sample PHP quick start.
Use a tenant application with a google-oauth2 connection and the Auth0 Authorization extension installed (which should add the auth0-authorization-extension rule to the Auth Pipeline.

**Comment by evansims** [comment]
Hi @devops-at-alinea 👋 Thanks for your issue!

Are you running the script behind a separate HTTP/proxy server, or are you interacting with the PHP -S option directly?

**Comment by devops-at-alinea** [comment]
Hi evansims,

Apologies for the delay - been off for a week. 
I'm using Apache 2.4 and I'm not behind any proxy (that I'm aware of).

**Comment by evansims** [comment]
This is related to Apache's configuration. You'll need to check their documentation on how to increase their cookie size limitations.

**Comment by brosenberger** [comment]
@devops-at-alinea hi, i had a the same issue with my php solution (got the same header issues as to many cookies have been set), i migrated from cookiestore to sessionstore and it worked, see the examples provided: https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md#php-session-storage
