### ISSUE TITLE
Breaking change in minor update

### ISSUE THREAD

**Issue by pkruithof** [auth0/auth0-PHP#711]
### Checklist

- [X] The issue can be reproduced in a a sample app (either [webapp](https://github.com/auth0-samples/auth0-php-web-app) or [api](https://github.com/auth0-samples/auth0-php-api-samples)) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-PHP#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-PHP/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-PHP/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-php) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.5

### PHP Version

PHP 8.2

### Description

In v8.5.0 the `Auth0\SDK\Utility\HttpRequest::addPath()` method has a changed signature:

before:
```
public function addPath(
         ?string ...$params,
     ): self { }
```

after:
```
public function addPath(
        array $params = [],
    ): self { }
```

This change happened in https://github.com/auth0/auth0-PHP/commit/6a87d7224986576393440e83d5829c02e5fbf01a#diff-b219f4631c9d44643cfc8f80e9906eadcda124569f4b1006049e5960dd724534R214, and does not seem to be documented. Although it's not stated explicitly in the readme (as far as I can see) I assume this project adheres to semantic versioning. In that case I would expect this to be a change for a major version, and preferably preceded by a deprecation warning.

Not a bug per se, but it might break existing customer's installations.

### How can we reproduce this issue?

```php
$request = new \Auth0\SDK\Utility\HttpRequest(
    $configuration,
    1,
    'PUT'
);
$request->addPath('foo', 'bar');
```

**Comment by evansims** [comment]
Hi @pkruithof 👋 You're quite right, thanks for bringing that to my attention.  We do try to follow semver whenever possible. In this case, that appears to have been an unintended change caused by the new code styling linter rules, and was applied erroneously.

That said, as HttpRequest is an internal API that customers generally shouldn't be engaging with directly, I don't expect the change will affect anyone in real-world use. Still, if we do end up getting feedback otherwise I'm certainly happy to cut a bugfix release and revert that.

Thanks for the heads up!

**Comment by pkruithof** [comment]
We use it to automatically apply some settings for our account, as part of the "infrastructure as code" setup. For example to set the universal login template:

```php
$this
    ->api()
    ->method('PUT')
    ->addPath(['branding', 'templates', 'universal-login'])
    ->withBody(['template' => $template])
```

I don't see a different way to call (a lot of) the management API methods other than this. Anyway, I'm glad our CI caught this before merging the update 😉
