### ISSUE TITLE
use final-annotation instead of hard-final

### ISSUE THREAD

**Issue by leberknecht** [auth0/auth0-PHP#727]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.7

### PHP Version

PHP 8.2

### Description

Hi,
Not a bug but a suggestion: It would be great if you could switch from hard-final to annotation-level `@final`, so the lib can be mocked during testing without the hassle of creating wrapper classes.
Also suggested here https://verraes.net/2014/05/final-classes-in-php/ and many other fighters of "lets make everything  `final` per default"

### How can we reproduce this issue?

Try to use the lib in a project and then mock it during testing. Maybe this is a good time to extend the `tests` of the sample application a bit, atm they are not doing anything meaningful :)

**Comment by evansims** [comment]
Hi @leberknecht, thanks for your suggestion! We offer interfaces for all our SDK classes, which allows for the mocking capacity you're looking for. We aren't considering changing this behavior at this time.
