### ISSUE TITLE
JWT generator: wrong header key "type"

### ISSUE THREAD

**Issue by tricki** [auth0/auth0-PHP#728]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.7

### PHP Version

PHP 8.1

### Description

I'm trying to use `\Auth0\SDK\Token\Generator` to generate a JWT (to return to an Action in Auth0) but kept getting this error:

> Error: The session token is invalid: Unexpected token payload type

I solved it by manually adding `"typ": "JWT"` to the header. The [Generator class instead adds a `"type": "JWT"` to the header](https://github.com/auth0/auth0-PHP/blob/main/src/Token/Generator.php#L91). I suspect that should be changed to "typ".

Note: I'm using Auth0-PHP in a Laravel app through `auth0/login`, but am using `Generator` directly.

### How can we reproduce this issue?

```php
$token = \Auth0\SDK\Token\Generator::create(
    signingKey: 'MY_SECRET',
    algorithm: Token::ALGO_HS256,
    claims: [
        // ...
    ],
    headers: ['typ' => 'JWT'], // this line makes the token valid
);
```

**Comment by evansims** [comment]
Good catch; thanks for reporting this! I've created a PR fixing the issue. I'll merge and release the fix once our team has an opportunity to review the changes.
