### ISSUE TITLE
Specify GuzzleHttp config

### ISSUE THREAD

**Issue by dev101** [auth0/auth0-PHP#73]
There is no easy way to specify [GuzzleHttp config options](http://guzzle3.readthedocs.org/http-client/client.html#configuration-options), e.g. **proxy server** to be used.

**Comment by glena** [comment]
good catch, I will try to push this by end of week

**Comment by glena** [comment]
Done, v `3.1.0` (PR #74)

**Comment by dev101** [comment]
:v:
