### ISSUE TITLE
/tokeninfo API support

### ISSUE THREAD

**Issue by doapp-ryanp** [auth0/auth0-PHP#76]
Does this SDK support making calls to `/tokeninfo` with a user's JWT token? 

I can't find support for either of the [User profile](https://auth0.com/docs/auth-api#user-profile) endpoints in this SDK

**Comment by glena** [comment]
it is not part of the public api, but it will fetch the user profile after the token exchange and, if you enable it, store it in the user session https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L261

**Comment by doapp-ryanp** [comment]
ok thanks
