### ISSUE TITLE
ClientAssertionGenerator has a static expiry of 180 seconds. 

### ISSUE THREAD

**Issue by danrossi** [auth0/auth0-PHP#762]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.7

### PHP Version

PHP 8.2

### Description

I'm trying to mock up using the api to generate RS tokens to be validated from a java backend using auth0 java library. I have a backend I need to show php examples how to generate tokens. However it can't be done from the main api, the method has to be used directly. Most of it is tied to verification and http requests rather than just uncoupled token generation. The sample app doesn't generate api tokens just verifies. 

The java library is much more concise generating tokens than the php one.

I found this method has a static expiry so can't be used. So the internal Generate api needs to be used and all that code duplicated and made external. Expiry needs to be a configuration perhaps ? 

### How can we reproduce this issue?

https://github.com/auth0/auth0-PHP/blob/cc7abb9a739ff7ad966f1921dd0a5b2b1521863e/src/Token/ClientAssertionGenerator.php#L56

**Comment by evansims** [comment]
Hi @danrossi 👋 

The `ClientAssertionGenerator` is only intended for generating JSON Web Token Client Assertions, otherwise known as  "private key JWTs." https://auth0.com/docs/get-started/authentication-and-authorization-flow/authenticate-with-private-key-jwt

It sounds like you want a more general-purpose token generator of some kind. Could you clarify your use case a bit for me, and perhaps I can help?
