### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by ihabkhaled** [auth0/auth0-PHP#763]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.7

### PHP Version

PHP 8.2

### Description

![image](https://github.com/auth0/auth0-PHP/assets/39255494/0ca06216-e892-4c2b-8614-f08373231019)
I am trying to login but in the callback I have this error
I tried to add dd() inside ewxchange function

the $pkce variable is not set
$pkce = $store->getOnce('code_verifier');

![image](https://github.com/auth0/auth0-PHP/assets/39255494/a3b334d2-300c-48c2-8c3a-c9d77dd455ec)

![image](https://github.com/auth0/auth0-PHP/assets/39255494/02eb1b03-6093-425c-a87d-e30ae9c2cdca)

I am using version 7.14 auth0/login
"name": "auth0/auth0-php",
            "version": "8.11.1",

Itried this command php artisan key:generate

I tried it and it bypassed
now I have another issue but the issue persists again 

![image](https://github.com/auth0/auth0-PHP/assets/39255494/5ccf40aa-6940-4a73-987a-eb0f4a3a3ad1)

### How can we reproduce this issue?

Reproduction
1-login
2-the call back url

**Comment by ihabkhaled** [comment]
env file

AUTH0_DOMAIN=dev-u37mpzobnwula3ip.us.auth0.com
AUTH0_CLIENT_ID=<client id i removed it from here>
AUTH0_CLIENT_SECRET=<SECRET>
AUTH0_CALLBACK_URL=http://127.0.0.1:8000/callback
AUTH0_BASE_URL=http://127.0.0.1:8000
APP_URL=http://127.0.0.1:8000

**Comment by ihabkhaled** [comment]
APP_NAME=Laravel
APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:uj8tdbIm2n6Fr3U9jXM4TlN4Bk9RXObJXPIkxEUimkQ=

**Comment by evansims** [comment]
Hi @ihabkhaled 👋 This issue would be better raised in the [Laravel SDK repository](https://github.com/auth0/laravel-auth0), as it does not involve the PHP SDK.

In any event, the cURL error you're seeing is not SDK-related. The error indicates the DNS resolution on the server you are executing PHP from is unable to resolve the hostname correctly. This is a server configuration issue, and is not something the SDK influences.
