### ISSUE TITLE
Callback never called

### ISSUE THREAD

**Issue by midnite81** [auth0/auth0-PHP#768]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

Other (specify below)

### PHP Version

Other (specify below)

### Description

SDK version: auth0/auth0-php 8.11.1 PHP SDK for Auth0 Authentication and Management APIs.
PHP version: PHP 8.3.9

In this file, src/Utility/HttpRequest.php, it checks to see if a method exists on the $mockedResponse object but it's not a method, it's a property, so this will always return false. I am happy to create a PR for this but I wanted just to make sure I wasn't doing something wrong in the first place. 

From: src/Utility/HttpRequest.php
```php
 if ($mockedResponse && method_exists($mockedResponse, 'callback') && is_callable($mockedResponse->callback)) { // @phpstan-ignore-line
                ($mockedResponse->callback)($httpRequest, $httpResponse);
            }
```

### How can we reproduce this issue?

If you create a mock, you'll find the closure is never run. For example; 

```php
   $service->getHttpClient()->mockResponse(
            $this->createResponseInterface(),
            function ($request) {
                $this->assertEquals('/api/v2/users', $request->getUri()->getPath());
            }
        );
```

**Comment by evansims** [comment]
Thanks for reporting and patching this, @midnite81! The contribution is much appreciated.
