### ISSUE TITLE
Laravel telescope infinite loop issue.

### ISSUE THREAD

**Issue by Sherzod-tech** [auth0/auth0-PHP#780]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.1

### PHP Version

PHP 8.1

### Description

Using laravel telescope with auth0/login cause infinite loop. I searched and found closed issue https://github.com/auth0/laravel-auth0/issues/412 I tried every steps mentioned. Even turn off event and query and other watchers but still same issue until disable telescope

### How can we reproduce this issue?

Create php 8.1 laravel 10 project  with auth0/login version 7.12 SDK with web and M2M applicatoin. And Install and enable laravel telescope and use any test api request using auth0 middleware.

**Comment by kishore7snehil** [comment]
@Sherzod-tech  Please go through this [documentation](https://github.com/auth0/laravel-auth0/blob/main/docs/Telescope.md) as there is already a workaround suggested which will help you to resolve this issue.
