### ISSUE TITLE
Create password change ticket fails

### ISSUE THREAD

**Issue by brightbeagle** [auth0/auth0-PHP#84]
src/API/Management/Tickets.php

Method createPasswordChangeTicket, the apiClient post header is missing 'application/json', resulting in a invalid body error.  

Also, the method should have a default value of null for $new_password, and should only get added to $body if not null, as the new password field is optional in the API.

**Comment by glena** [comment]
You are right, it should be fixed by `3.3.4`.

let me know how it goes after the upgrade. Thx for reporting

**Comment by brightbeagle** [comment]
Haven't tried it yet, but I think you are still going to need to add 'application/json' to the apiClient post:

```
return $this->apiClient->post()
            ->tickets()
            ->addPath('password-change')
            ->withHeader(new ContentType('application/json'))
            ->withBody(json_encode($body))
            ->call();
```

**Comment by glena** [comment]
Shoot, you are right, try `3.3.5`. Sorry about that

**Comment by brightbeagle** [comment]
Worked on 3.3.5. Thanks.
