### ISSUE TITLE
More descriptive error message when code exchange fails

### ISSUE THREAD

**Issue by rolodato** [auth0/auth0-PHP#86]
Would be helpful to show the full response/status from Auth0 here: https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L246-L248. If there's a misconfiguration such as wrong client secret, redirect URI, etc. retrying the login won't help.

**Comment by glena** [comment]
done, ready for the next release

**Comment by glena** [comment]
`3.4.0`
