### ISSUE TITLE
More descriptive readme file with instructions about how to download dependencies using composeri

### ISSUE THREAD

**Issue by fiannolo** [auth0/auth0-PHP#88]
After downloading this seed project, the readme file doesn't specify the path to get all the dependencies needed for the project in order to work properly. The existing text in the readme file in the 'Running this example' section is:

#Running the example
In order to run the example you need to have `composer` and `php` installed.

You also need to set the ClientSecret, ClientId, Domain and Callback URL for your Auth0 app as environment variables with the following names respectively: `AUTH0_CLIENT_SECRET`, `AUTH0_CLIENT_ID`, `AUTH0_DOMAIN` and `AUTH0_CALLBACK_URL`.

For that, if you just create a file named `.env` in the directory and set the values like the following, the app will just work:

````bash
# .env file
AUTH0_CLIENT_SECRET=myCoolSecret
AUTH0_CLIENT_ID=myCoolClientId
AUTH0_DOMAIN=yourDomain.auth0.com
AUTH0_CALLBACK_URL=http://your.url/
````

Once you've set those 4 environment variables, just run the following to get the app started:

````bash
composer install
php -S localhost:3000
````

So I suggest to add the information existing in the tutorial which specify after the instalation of composer, to run the following command:
````
To install dependencies, run the following

composer require auth0/auth0-php:"~3.0"
````

**Comment by glena** [comment]
I added a line on how to install using composer in the README.

Anyway, it points to the auth0 docs which I think they are pretty clear.

If you think it can be improved in some other way, PRs are always welcome :)
