### ISSUE TITLE
PHP Fatal error:  Class 'Auth0\SDK\API\ApiUsers' not found in vendor/auth0/auth0-php/src/Auth0.php on line 256

### ISSUE THREAD

**Issue by MarkPfennig** [auth0/auth0-PHP#9]
PHP Fatal error:  Class 'Auth0\SDK\API\ApiUsers' not found in vendor/auth0/auth0-php/src/Auth0.php on line 256

using both 1.0 branch and master.

**Comment by MarkPfennig** [comment]
appears to be autoloading issue on classes in \API namespace via composer.

    use Auth0\SDK\Auth0; new Auth0(); // works fine
    use Auth0\SDK\API\ApiUsers; new ApiUsers; // fatal error
    use Auth0\SDK\API\ApiClient; new ApiClient; // fatal error

**Comment by MarkPfennig** [comment]
Could be a composer psr-4 word casing issue?

Can work around this issue temporarily by `require`'ing all dependent files.

Can confirm that composer autoloader works for all other vendor packages.

**Comment by glena** [comment]
Fixed on 1.0.3

**Comment by AdelekeIO** [comment]
Pls can i get help with this issue: Fatal error: Uncaught exception 'Auth0\SDK\Exception\CoreException' with message 'Invalid domain' in C:\xampp\htdocs\00-starter-seed\vendor\auth0\auth0-php\src\Auth0.php:213 Stack trace: #0 C:\xampp\htdocs\00-starter-seed\index.php(30): Auth0\SDK\Auth0->__construct(Array) #1 {main} thrown in C:\xampp\htdocs\00-starter-seed\vendor\auth0\auth0-php\src\Auth0.php on line 213

**Comment by joshcanhelp** [comment]
@AdelekeIO - When you initialize the `Auth0` class, you need to pass in a domain, among other things. Lots of information on the [README for this repo](https://github.com/auth0/auth0-PHP#login).
