### ISSUE TITLE
Package guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by rnicholls** [auth0/auth0-PHP#91]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by rnicholls** [comment]
3.4

**Comment by glena** [comment]
really?

3.4 is using `guzzlehttp/guzzle` check https://packagist.org/packages/auth0/auth0-php and https://github.com/auth0/auth0-PHP/blob/3.4.0/composer.json#L14

**Comment by rnicholls** [comment]
let me clear my cache / uninstall and see if that fixes the issue.

**Comment by rnicholls** [comment]
Yup, that was it, needed to do a remove / clear-cache from an older version. Sorry about that.

**Comment by glena** [comment]
weird, but thx anyway :)
