### ISSUE TITLE
Logs mgmt api missing?

### ISSUE THREAD

**Issue by dev101** [auth0/auth0-PHP#95]
Any reason why [logs management api](https://auth0.com/docs/api/management/v2#!/Logs/get_logs) is not covered?
I wish PHP client was [on par](https://github.com/auth0/node-auth0/blob/master/src/management/LogsManager.js) with Node client.

**Comment by glena** [comment]
> Any reason why logs management api is not covered?

seems it felt into the cracks
I will work on it when I have some free time (probably next week). PRs will be really appreciated too.

thx for reporting

**Comment by glena** [comment]
It will be ready on the next release (`4.0.0`), I will let you know when it is ready

**Comment by glena** [comment]
v4 was released.

There are some classes soon to be deprecated, check the readme for more info (o the classes comments)
