### ISSUE TITLE
Please add a way to set CURL_IPRESOLVE_V4 in Guzzle

### ISSUE THREAD

**Issue by udf2457** [auth0/auth0-PHP#98]
Hi,

Please can you add a way to enable "CURL_IPRESOLVE_V4" as a custom cURL option in Guzzle ? (http://docs.guzzlephp.org/en/latest/faq.html#how-can-i-add-custom-curl-options)

Calling auth0 on my system takes an eternity, and the correct way to solve this is setting CURL_IPRESOLVE_V4 in PHP cURL.

**Comment by glena** [comment]
You should be able to do it using the `guzzleOptions` (http://docs.guzzlephp.org/en/latest/faq.html?highlight=curl#how-can-i-add-custom-curl-options) parameter when you initialize `Auth0Api`.

```
$token = "eyJhbGciO....eyJhdWQiOiI....1ZVDisdL...";
$domain = "account.auth0.com";
$guzzleOptions = [
    'curl' => [
        CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4
    ]
];

$auth0Api = new \Auth0\SDK\Auth0Api($token, $domain, $guzzleOptions); /* $guzzleOptions is optional */

$usersList = $auth0Api->users->search([ "q" => "email@test.com" ]);
```

**Comment by udf2457** [comment]
Interesting. Will play around with that.  Thanks !

**Comment by glena** [comment]
FYI, This `guzzleOptions` is being set to guzzle here https://github.com/auth0/auth0-PHP/blob/master/src/API/Helpers/RequestBuilder.php#L114

**Comment by glena** [comment]
@udf2457  were you able to make it work?
